#!/usr/bin/env python3

import argparse
import sys

from morphgnt.utils import load_wordset
from morphgnt.utils import nfkc_normalize as n


def is_word_unicode_normalized(f, word):
    norm_word = n(word)
    if word == norm_word:
        return 0
    else:
        print("Word {} shall be normalized as {}.".format(word, norm_word), file=f)
        return 1


f = sys.stderr
e = 0 # exit status

argparser = argparse.ArgumentParser()
argparser.add_argument("wordset", help="word set file")

args = argparser.parse_args()
wordset = load_wordset(args.wordset)

for word in wordset:
    e = is_word_unicode_normalized(f, word) or e

sys.exit(e)
