#!/usr/bin/env python3

import argparse
import sys

import yaml

from morphgnt.utils import load_wordset


def is_word_a_lexeme_in_lexemes_file(f, word, lexemes):
    if word in lexemes:
        return 0
    else:
        print("Word {} shall be removed from the set because not among lexemes in lexemes file.".format(word), file=f)
        return 1


f = sys.stderr
e = 0 # exit status

argparser = argparse.ArgumentParser()
argparser.add_argument("wordset", help="word set file")
argparser.add_argument("lexemes", type=argparse.FileType('r'), help="lexemes file")

args = argparser.parse_args()
wordset = load_wordset(args.wordset)
lexemes = yaml.load(args.lexemes)

for word in wordset:
    e = is_word_a_lexeme_in_lexemes_file(f, word, lexemes) or e

sys.exit(e)
