#!/usr/bin/env python

import argparse
import sys

from morphgnt.utils import load_wordset
from morphgnt.utils import nfkc_normalize as n


def is_word_unicode_normalized(f, word):
    norm_word = n(word)
    if word == norm_word:
        return 0
    else:
        print >>f, "Word {} shall be normalized as {}.".format(word.encode("utf-8"), norm_word.encode("utf-8"))
        return 1


f = sys.stderr
e = 0 # exit status

argparser = argparse.ArgumentParser()
argparser.add_argument("wordset", help="word set file")

args = argparser.parse_args()
wordset = load_wordset(args.wordset)

for word in wordset:
    e = e or is_word_unicode_normalized(f, word.decode("utf-8"))

sys.exit(e)
