#!/usr/bin/env python
# coding: utf-8

import re

from morphgnt.utils import load_yaml, sorted_items

regex_templates = {
    "greek": ur"[\u0370-\u03FF\u1F00-\u1FFF]+",
    "gloss": ur"‘[^’]+’",
    "text": ur"[A-Za-z0-9.,/\- ]+",
    "latin": ur"[A-Za-z]+",
    "pie": ur"\*[a-z]+",
    "skt": ur"[a-zá]+",
    "ref": ur"(?:Mt|Ac) \d+:\d+",
    "see": ur"s\.|see",
    "prec": ur"prec\.|preceding",
}

regexes = [
    ur"(orig|etym)\. (complex|not determined|obscure|unclear|uncertain|unknown)$",
    ur"=Attic {greek}$",
    ur"=Lat\. {latin} {latin}$",
    ur"=next entry$",
    ur"=older {greek} /{greek}, fem\. of {greek}$",
    ur"={greek}$",
    ur"=ὁ {greek} {gloss}; {see} {greek}$",
    ur"a city named in honor of Antipater, procurator of Judea under Julius Caesar$",
    ur"a common name$",
    ur"a Greek name$",
    ur"an onomatopoetic word ={gloss}, sim\. Lat\. {latin}; {text} {gloss}$",
    ur"apparently of foreign orig\.$",
    ur"apparently of Heb\. orig\.$",
    ur"Aram\. ={text}; {see} explanation {ref}$",
    ur"Aram\. term ={gloss}$",
    ur"Aram\. {gloss}$",
    ur"Aram\. {gloss}; a common name$",
    ur"Aram\.$",
    ur"Aram\., prob\. ={text} {gloss}, i\. e\. {text}$",
    ur"assoc\. w\. {greek} {text}, pl\. as in {greek} {gloss}$",
    ur"assoc\. w\. {greek}; {gloss}, also {gloss}$",
    ur"Attic form ={greek}, etym\. uncertain$",
    ur"Attic form of {greek}$",
    ur"by- form of {greek} \({greek}, {greek} {gloss}\)$",
    ur"by- form of {greek}$",
    ur"by- form of {greek}; {gloss}$",
    ur"contracted from {greek} \(ἀ- priv\., {greek}\) {gloss}$",
    ur"Coptic loanword$",
    ur"cp\. epic noun {greek} and Attic {greek}, both {gloss}$",
    ur"cp\. epic {greek} {gloss}; {gloss}$",
    ur"cp\. Homeric {greek} {gloss}$",
    ur"cp\. Lat\. {latin} {gloss}$",
    ur"cp\. Lat\. {latin} {gloss}; in the strict sense:{text}; the synonym {greek} in the strict sense refers to {gloss} or {gloss}, {text}. Usage in the NT is much more fluid.$",
    ur"cp\. Lat\. {latin}$",
    ur"cp\. Skt\. {skt} {gloss}$",
    ur"cp\. Skt\. {skt} {gloss}, Lat\. {latin}$",
    ur"cp\. the adj. {greek} {gloss}; {text}$",
    ur"cp\. the epic form {greek} {gloss}; rare in the nt\. form$",
    ur"cp\. {greek} and {greek} in sense of {gloss}$",
    ur"cp\. {greek} and {greek}$",
    ur"cp\. {greek} in sense of {gloss} {text} ={gloss}; {see} {greek}$",
    ur"cp\. {greek} opp\. {greek}$",
    ur"cp\. {greek} {gloss} and {greek}$",
    ur"cp\. {greek} {gloss} and {see} {greek}$",
    ur"cp\. {greek} {gloss} in Persia$",
    ur"cp\. {greek} {gloss}$",
    ur"cp\. {greek} {gloss}, {text}; cp\. our {gloss} in ref\. to {text}$",
    ur"cp\. {greek}$",
    ur"cp\. {greek}, {greek} ‘.+’ fr\. {greek}$",
    ur"cp\. {greek}, {greek}$",
    ur"cp\. {greek}; Lat\. {latin} {gloss}$",
    ur"cp\. {greek}; mostly in pl\. {gloss}$",
    ur"cp\. {greek}; {gloss} {text}$",
    ur"cp\. {greek}; {gloss}$",
    ur"cp\. {greek}; {gloss}, {text}$",
    ur"cp\. {prec} entries$",
    ur"cp\. {prec}$",
    ur"derivation undetermined, but a root signifying {gloss} or {gloss} has claimed attention$",
    ur"derived from {greek}, {text}$",
    ur"dim\. of {greek}$",
    ur"etym\. (complex|unclear|uncertain); {gloss}$",
    ur"etym\. complex, cp\. {text} {gloss}$",
    ur"etym\. complex; prim\. {gloss} {text}$",
    ur"etym\. uncertain, cp\. {greek} {gloss}$",
    ur"etym\. uncertain; the translation {greek} {greek} {ref} may reflect popular etym\.$",
    ur"etym\. uncertain; {text}$",
    ur"etym\. uncertain; {text}:{text}$",
    ur"etym\. unclear \(many conflicting theories\), cp\. {greek} {gloss}$",
    ur"etym\. unclear; the NT shows a preference for {greek}$",
    ur"etym\. unclear; two major significations:{gloss} with raw materials, {gloss} esp\. of athletic exercise$",
    ur"etym\. unclear; {text}, in appearance like a {gloss}, the primary meaning of {greek}\.$",
    ur"etym\. undetermined; freq\. in Homer of {gloss} or {gloss} {text}$",
    ur"etymol\. unknown$",
    ur"folk- etymology \(ἀ- priv\., {greek} o {greek}\) underlies the Gk\. formation of this foreign word, suggesting perh\. {gloss}$",
    ur"folk- etymology \(ἀ- priv\., {greek}\) underlies the Gk\. formation of this foreign word, suggesting perh\. {gloss}$",
    ur"for older {greek}$",
    ur"formally the pres\. ptc\. of {greek}$",
    ur"fr\. the fut\. of {greek}, {greek}$",
    ur"fr\. {text} {greek}$",
    ur"freq\. as v\. l\. for {greek}$",
    ur"from the adj\. {greek} ‘[^’]+$",
    ur"Heb\. name, hence {gloss}$",
    ur"Heb\. {gloss}$",
    ur"Heb\.$",
    ur"Heb\., of uncertain etymology$",
    ur"Heb\.; cp\. modern Gk\. ἀ\. {gloss}$",
    ur"Heb\.; {text} {gloss}$",
    ur"I\. {greek}$",
    ur"IE {pie}, cp\. {greek} {gloss}$",
    ur"IE$",
    ur"IE, cp\. Lat\. {latin}$",
    ur"IE; mostly used by poets$",
    ur"IE; var\. senses in Gk\. lit\.$",
    ur"IE; {text}:{text}$",
    ur"in older Gk\. also {greek}$",
    ur"Lat\. loanword:{gloss}, {text} ={text}$",
    ur"Lat\. orig\.; {text}$",
    ur"Lat\. {latin} {gloss}; {gloss}; {text}$",
    ur"late by- form of {greek}$",
    ur"later form of {greek} in same sense$",
    ur"later form of {greek}:ἀ- priv\., {greek} {gloss}$",
    ur"later form of {greek}\. IE, cp\. {greek}$",
    ur"later word for {greek} and freq\. w\. {greek} as v\. l\.$",
    ur"MT",
    ur"name of {text}$",
    ur"named after {text}$",
    ur"noun from the adj\. {greek}, cp\. {greek}$",
    ur"nt\. comp\. of {greek} {gloss}$",
    ur"of Oriental origin, prob\. via Egypt; {gloss}, {text}$",
    ur"of Sanskrit origin, cp\. Lat\. {latin} {gloss}$",
    ur"opp\. {greek} {gloss}$",
    ur"orig\. uncertain, akin to {greek}$",
    ur"orig\. uncertain, but cp\. {greek} {gloss}; {gloss}$",
    ur"orig\. uncertain; {text}$",
    ur"orig\. unclear; {text}$",
    ur"orig\. undetermined; {text}$",
    ur"perh\. short for {greek}$",
    ur"prob\. of foreign origin$",
    ur"proper name in form of a participle from {greek}$",
    ur"properly nt\. gen\. of {greek}$",
    ur"Roman cognomen$",
    ur"Semitic assoc\.; frequently referenced by Herodotus$",
    ur"Semitic orig\.$",
    ur"Skt\. =Lat\. {latin} {gloss}$",
    ur"Skt\. assoc\. in sense of {gloss}$",
    ur"Skt\. assoc\.$",
    ur"Skt\. assoc\., cp\. Lat\. {latin} {gloss}$",
    ur"Skt\. assoc\., cp\. {greek} /{greek} /{greek} {gloss}; orig\. {gloss}, then {gloss}$",
    ur"Skt\. assoc\., cp\. {greek} {gloss}; in Homer both as {gloss} and {gloss}$",
    ur"Skt\. assoc\., cp\. {greek}$",
    ur"Skt\. assoc\.; {text} \(esp\. of {text}\) {gloss}, {text} {gloss}$",
    ur"Skt\. via Heb\.$",
    ur"Skt\. {skt} {gloss}$",
    ur"Skt\. {skt} {gloss}, Lat\. {latin} {gloss}; prim\. in local sense {gloss}$",
    ur"Skt\. {skt} · {gloss}$",
    ur"the form and textual history of this name is complex$",
    ur"{greek} ={greek} \({see} {greek}\), {greek}$",
    ur"{greek} \(={greek}\); {gloss}$",
    ur"{greek} \(w\. focus on separation\), {greek} {gloss}, freq\. with connotation of {text}$",
    ur"{greek} \({greek} and {greek} via the aor\. pass\. inf\. {greek}\)$",
    ur"{greek} \({greek}, {greek} {gloss}, {greek}\) {gloss}$",
    ur"{greek} \({greek}, {greek} {gloss}\) {gloss}$",
    ur"{greek} \({greek}, {greek}\) {gloss}$",
    ur"{greek} \({greek}, {greek}\) {gloss}, {text}$",
    ur"{greek} \(ἀ- priv\., {greek} o {greek}\) {gloss}$",
    ur"{greek} \(ἀ- priv\., {greek} ‘[^’]+\) {gloss}$",
    ur"{greek} \(ἀ- priv\., {greek}\) {gloss}$",
    ur"{greek} \(ἀ- priv\., {greek}\) {gloss}, fr\. {greek}$",
    ur"{greek} \(ἀ- priv\., {greek}\); {gloss} i\. e\. {gloss}$",
    ur"{greek} \+a root with focus on independent action; ‘.+’$",
    ur"{greek} fr\. {greek}$",
    ur"{greek} gener\. =‘.+’$",
    ur"{greek} in sense of {gloss}, {greek}$",
    ur"{greek} ordinarily in the sense {gloss}$",
    ur"{greek} with connotation of {gloss}, {greek}$",
    ur"{greek} with its full force, {greek} {gloss}$",
    ur"{greek} with perfective force, {greek}$",
    ur"{greek} {gloss} fr\. an older ptc\. form and and connected with {greek}$",
    ur"{greek} {gloss} fr\. {greek} a later form of {greek}$",
    ur"{greek} {gloss} {text}$",
    ur"{greek} {gloss} {text}$",
    ur"{greek} {gloss} {text}:to be {greek} \(ἀ- priv\.\) means that one {text}; {gloss}$",
    ur"{greek} {gloss}$",
    ur"{greek} {gloss}, cp\. {greek} {gloss}; in sense ranging from {gloss} to {gloss}$",
    ur"{greek} {gloss}, cp\. {greek}$",
    ur"{greek} {gloss}, cp\. {greek}, {greek} {gloss}$",
    ur"{greek} {gloss}, mid\. {gloss}$",
    ur"{greek} {gloss}, not to be confused with the homograph {greek} {gloss}$",
    ur"{greek} {gloss}, the prefix {greek} emphasizes {text}$",
    ur"{greek} {gloss}, then {gloss} {text}$",
    ur"{greek} {gloss}, {greek} {gloss} {text} {greek} {gloss}$",
    ur"{greek} {gloss}, {greek} {gloss}$",
    ur"{greek} {gloss}, {greek} {gloss}; {gloss}$",
    ur"{greek} {gloss}, {greek} {gloss}; {text}$",
    ur"{greek} {gloss}, {greek}; {gloss}$",
    ur"{greek} {gloss}, {greek}; {gloss}, {text}$",
    ur"{greek} {gloss}, {greek}; {text}$",
    ur"{greek} {gloss}, {text}$",
    ur"{greek} {gloss}; in non- biblical authors freq\. in sense of {gloss}$",
    ur"{greek} {gloss}; mid\. of joining pers\., ordinarily in the sense {gloss}$",
    ur"{greek} {gloss}; prim\. {gloss} esp\. as {gloss} {text}$",
    ur"{greek} {gloss}; {gloss}$",
    ur"{greek} {gloss}; {gloss}, also of foods in var\. senses of {gloss}, hence {gloss}$",
    ur"{greek} {gloss}; {gloss}, {gloss} {text} {gloss} {text}$",
    ur"{greek} {gloss}; {gloss}, {text} {gloss}$",
    ur"{greek} {gloss}; {text}:{text}$",
    ur"{greek} {text}$",
    ur"{greek}$",
    ur"{greek}, \*{greek}$",
    ur"{greek}, addition of {greek} indicates {text}$",
    ur"{greek}, an adj\. {gloss}, {text} \({text}\) \+{greek} \({greek}\) {gloss} \(hence {gloss}\)$",
    ur"{greek}, cp\. {greek} \({greek}, {greek}\) {gloss}$",
    ur"{greek}, cp\. {greek}$",
    ur"{greek}, cp\. {greek}; ={greek}, which is preferred in later Gk\.$",
    ur"{greek}, Gk\. deity$",
    ur"{greek}, in early Gk. {gloss}$",
    ur"{greek}, originally nt\. pl\. of {greek} with change in accent reflecting emphasis {gloss}; stronger than {greek}$",
    ur"{greek}, the term for {text} in Hittite and Egyptian texts and Homer$",
    ur"{greek}, {greek} /{greek} {gloss}, hence {greek} signifies close of pregnancy$",
    ur"{greek}, {greek} \(no present in use\)$",
    ur"{greek}, {greek} \({greek} \+{greek}\) {gloss} fr\. {greek}; {gloss}$",
    ur"{greek}, {greek} fr\. {greek} \({greek}\) {gloss}$",
    ur"{greek}, {greek} fr\. {greek}$",
    ur"{greek}, {greek} fr\. {greek}, cp\. {greek} {gloss}$",
    ur"{greek}, {greek} fr\. {greek}; in later Gk\. {greek} gives way to {greek}$",
    ur"{greek}, {greek} fr\. {greek}; {gloss}$",
    ur"{greek}, {greek} fr\. {greek}; {gloss}, hence {gloss}$",
    ur"{greek}, {greek} via the mid\.$",
    ur"{greek}, {greek} via {greek} {gloss}, in various senses, including {text} as {gloss} and {gloss}$",
    ur"{greek}, {greek} via {greek}; the prefix, apparently redundant, makes the idea of {text} in {greek} explicit$",
    ur"{greek}, {greek} {gloss} ={text} {greek}$",
    ur"{greek}, {greek} {gloss} \(cp\. {greek}\)$",
    ur"{greek}, {greek} {gloss} also {gloss}, as compound fr\. {greek}$",
    ur"{greek}, {greek} {gloss} as in {text}$",
    ur"{greek}, {greek} {gloss} formed from the fut\. of {greek}, the compound fr\. {greek}$",
    ur"{greek}, {greek} {gloss} fr\. the mid\. of {greek}; {gloss}$",
    ur"{greek}, {greek} {gloss} fr\. {greek} {gloss}$",
    ur"{greek}, {greek} {gloss} fr\. {greek}$",
    ur"{greek}, {greek} {gloss} fr\. {greek}; {gloss}$",
    ur"{greek}, {greek} {gloss} or {gloss}$",
    ur"{greek}, {greek} {gloss} {text} fr\. {greek} {gloss}; {greek} has the force of {gloss}, i\. e\. {text}$",
    ur"{greek}, {greek} {gloss} {text}’; {greek} emphasizes {text}$",
    ur"{greek}, {greek} {gloss}$",
    ur"{greek}, {greek} {gloss}, as compound fr\. {greek}$",
    ur"{greek}, {greek} {gloss}, cp\. {greek}; {gloss}, hence {gloss}$",
    ur"{greek}, {greek} {gloss}, cp\. {greek}; {text}$",
    ur"{greek}, {greek} {gloss}, {text}$",
    ur"{greek}, {greek} {gloss}; intensive form ‘[^’]+$",
    ur"{greek}, {greek} {gloss}; prim\. {gloss}, {text}$",
    ur"{greek}, {greek} {gloss}; {gloss}$",
    ur"{greek}, {greek} {gloss}; {gloss}, hence {text}$",
    ur"{greek}, {greek} {text} ={gloss}$",
    ur"{greek}, {greek}$",
    ur"{greek}, {greek}, cp\. {greek} and {greek} {gloss}$",
    ur"{greek}, {greek}, cp\. {greek}$",
    ur"{greek}, {greek}, {greek} {gloss}$",
    ur"{greek}, {greek}; for older {greek}$",
    ur"{greek}, {greek}; in non- biblical Gk\. {greek} in this word signifies {gloss}; {gloss} ={gloss}$",
    ur"{greek}, {greek}; prim\. a commercial term$",
    ur"{greek}, {greek}; prim\. {gloss} then {gloss}, {text}$",
    ur"{greek}, {greek}; rarely found for the older {greek}$",
    ur"{greek}, {greek}; the idea of separation is strong in var\. senses including the act\. {gloss}, and the mid\. {gloss}, which implies a {greek} or {gloss} out of \({greek}\) a number of possibilities$",
    ur"{greek}, {greek}; the noun is more freq\. than the adj\. {greek}, {greek}$",
    ur"{greek}, {greek}; this 2 aor\. form is commonly used for the aor\. of {greek}$",
    ur"{greek}, {greek}; various senses in non- bibl\. Gk\.$",
    ur"{greek}, {greek}; {gloss} and so {gloss} on a specific object$",
    ur"{greek}, {greek}; {gloss} i\. e\. {gloss}$",
    ur"{greek}, {greek}; {gloss} {text}$",
    ur"{greek}, {greek}; {gloss}$",
    ur"{greek}, {greek}; {gloss}, e\. g\. {text}$",
    ur"{greek}, {greek}; {gloss}, hence {gloss}$",
    ur"{greek}, {greek}; {gloss}, then by extension {gloss}$",
    ur"{greek}, {greek}; {greek} expresses the opposite of {greek} {gloss} and focuses on separation, with such senses as {gloss}; mod\. Gk\. {gloss} from a position$",
    ur"{greek}, {greek}; {text} {gloss}$",
    ur"{greek}, {greek}; {text} {gloss}, hence {gloss} and so {gloss}$",
    ur"{greek}, {greek}; {text}$",
    ur"{greek}; =next entry$",
    ur"{greek}; a late form for {greek} {gloss}$",
    ur"{greek}; antonym {greek}$",
    ur"{greek}; any {gloss} or {gloss}$",
    ur"{greek}; freq\. in ins\. and pap\. of public servants$",
    ur"{greek}; in ancient Gk\. in var\. senses of a {gloss}, such as {text}$",
    ur"{greek}; in both a bad sense {gloss} and a good sense {gloss}$",
    ur"{greek}; in Hom\. {gloss}, then gener\. {gloss}$",
    ur"{greek}; only in biblical usage$",
    ur"{greek}; prim\. {gloss}, then {gloss}, {gloss}$",
    ur"{greek}; the form with accent on the second syllable signifies {gloss}, with accent on the final syllable {gloss}$",
    ur"{greek}; the suffix- {greek} may have affinity with {greek}, {greek} {gloss}, and related terms; {gloss}$",
    ur"{greek}; {gloss} {text}, {text} {gloss} {text}$",
    ur"{greek}; {gloss}$",
    ur"{greek}; {gloss}, esp\. {text}$",
    ur"{greek}; {gloss}, freq\. {text}$",
    ur"{greek}; {gloss}; cp\. {greek} {text} {gloss}$",
    ur"{greek}; {text}$",
    ur"{greek}; {text}, hence, {gloss}$",
    ur"{see} next entry on the etymology$",
    ur"{see} next$",
    ur"{see} {greek}$",
    ur"{see} {greek}$",
    ur"{see} {prec} entry$",
    ur"{see} {prec} {greek}- entries and two next entries$",
    ur"{see} {prec} {greek}- entries; the act\., which is not used in NT ={gloss}$",
    ur"{see} {prec}$",
    ur"{text}; {text} {greek} {gloss} {text} {gloss}; {text} {gloss}$",
    ur"ἀ- \(ἁ-\) copul\., {greek}$",
    ur"ἀ- copul\., {greek} {gloss} ={gloss}$",
    ur"ἀ- copul\., {greek} {gloss}$",
    ur"ἀ- priv, {greek}$",
    ur"ἀ- priv\. \(ἁ- by metathesis of aspiration\), {greek}, otherwise a word of uncertain orig\.$",
    ur"ἀ- priv\., cp\. {greek}, {text}$",
    ur"ἀ- priv\., fr\. {greek} via the fut\. mid\. form of {greek}:{greek}$",
    ur"ἀ- priv\., {greek} =Attic {greek} s$",
    ur"ἀ- priv\., {greek} ={greek} {gloss} {text}; {gloss}$",
    ur"ἀ- priv\., {greek} \({greek}, {greek} {gloss}\) {gloss} or \({greek}, {greek} {gloss} fr\. {greek} {gloss}\) {gloss}$",
    ur"ἀ- priv\., {greek} \({greek}, {greek}\) {gloss}$",
    ur"ἀ- priv\., {greek} \({greek}, {greek}\) {gloss}; {gloss}$",
    ur"ἀ- priv\., {greek} fr\. {greek}$",
    ur"ἀ- priv\., {greek} via 2 aor\. {greek}; {gloss}$",
    ur"ἀ- priv\., {greek} {gloss} fr\. {greek} {gloss}$",
    ur"ἀ- priv\., {greek} {gloss} fr\. {greek}$",
    ur"ἀ- priv\., {greek} {gloss} fr\. {greek}; lit\. {gloss}$",
    ur"ἀ- priv\., {greek} {gloss} fr\. {greek}; {gloss}$",
    ur"ἀ- priv\., {greek} {gloss}$",
    ur"ἀ- priv\., {greek} {gloss}, cp\. {greek}$",
    ur"ἀ- priv\., {greek} {gloss}, esp\. {text}$",
    ur"ἀ- priv\., {greek} {gloss}, fr\. {greek} via {greek} {gloss}$",
    ur"ἀ- priv\., {greek} {gloss}, freq\. in 3 sg\. {greek}$",
    ur"ἀ- priv\., {greek} {gloss}, {text}; {gloss}$",
    ur"ἀ- priv\., {greek} {gloss}; cp\. {greek} {gloss}$",
    ur"ἀ- priv\., {greek} {gloss}; {gloss}$",
    ur"ἀ- priv\., {greek} {gloss}; {gloss}, hence {gloss}$",
    ur"ἀ- priv\., {greek}$",
    ur"ἀ- priv\., {greek}, cp\. {greek} and {greek}$",
    ur"ἀ- priv\., {greek}, q\. v\., in sense of {gloss}; {text}$",
    ur"ἀ- priv\., {greek}, {greek} {gloss} fr. {greek}$",
    ur"ἀ- priv\., {greek}, {greek} {gloss}, cp\. {greek} {gloss}$",
    ur"ἀ- priv\., {greek}, {greek}$",
    ur"ἀ- priv\., {greek}; {gloss}$",
    ur"ἀ- priv\., {greek}; {gloss}, {text} {gloss} {text}$",
    ur"ἀ- priv\., {greek}; {text}$",
    ur"ἀ\.- priv\., {greek} \(used in the phrase {greek} {greek} {gloss}\) fr\. {greek}$",
    ur"ἀ\.- priv\., {greek}, cp\. {greek}$",
    ur"ἁ- copul\. {gloss} =Skt\. {skt}-, cp\. {greek} and oblique forms$",
    ur"ἁ- copul\., {greek} \(etym\. complex, with idea of {gloss}\) as in {greek} {gloss}; {gloss}$",
    ur"ἡ {greek} {gloss} and ὁ {greek} {gloss}, fr\. a common root:cp\. Lat\. {latin} {gloss}$",
    ur"ὁ {greek} {gloss}$",
]

compiled_regexes = []

for regex in regexes:
    for name, substitution in regex_templates.items():
        regex = re.sub("{{{}}}".format(name), substitution, regex)
    compiled_regexes.append(re.compile(regex))

danker = load_yaml("../data-cleanup/danker-concise-lexicon/components.yaml")

first_fail = None
count = 0

for lexeme, metadata in sorted_items(danker):
    components = metadata["components"]

    matched = False
    for compiled_regex in compiled_regexes:
        if compiled_regex.match(components):
            matched = True
            break

    if matched:
        count += 1
    else:
        if not first_fail:
            first_fail = (lexeme, components)

print "{}/{} = {}%".format(count, len(danker), int(1000 * count / len(danker)) / 10)
if first_fail:
    print first_fail[0]
    print first_fail[1]
