#!/usr/bin/env python
# coding: utf-8

import re
import sys

from morphgnt.utils import load_yaml, sorted_items

regex_templates = {
    "greek": ur"[\u0370-\u03FF\u1F00-\u1FFF]+",
    "gloss": ur"‘([^’]|’s )+’",
    "half-gloss": ur"‘[^’]+",
    "text": ur"[A-Za-z0-9.,/\-’(): ]+",
    "latin": ur"[A-Za-zō]+",
    "pie": ur"\*[a-z]+",
    "skt": ur"[a-záīā]+",
    "latvian": ur"[a-zô]+",
    "lithuanian": ur"[a-záž]+",
    "ref": ur"(?:Isaiah|Mt|Ac|Genesis|1 Chronicles) \d+:\d+(; \d+:\d+)*",
    "see": ur"s\.|see",
    "prec": ur"prec\.|preceding",
}

regexes = [

    ## contain greek

    # greek ;

    ur"{greek}$",

    ur"{greek} {gloss}; =the older {greek}$",
    ur"{greek} {gloss}; ={greek}$",
    ur"{greek} {gloss}; cognate of prec\. entry appearing first in Hom\.$",
    ur"{greek} {gloss}; in non- biblical authors freq\. in sense of {gloss}$",
    ur"{greek} {gloss}; late word for {greek} \({greek} {gloss}\)$",
    ur"{greek} {gloss}; later form of {greek}$",
    ur"{greek} {gloss}; mid\. of joining pers\., ordinarily in the sense {gloss}$",
    ur"{greek} {gloss}; prim\. {gloss} esp\. as {gloss} {text}$",
    ur"{greek} {gloss}; the suffix- {greek} expresses the result of an action; found only in eccl\. writing$",
    ur"{greek} {gloss}; {gloss}$",
    ur"{greek} {gloss}; {gloss}, also of foods in var\. senses of {gloss}, hence {gloss}$",
    ur"{greek} {gloss}; {gloss}, {gloss} {text} {gloss} {text}$",
    ur"{greek} {gloss}; {gloss}, {text} {gloss}$",
    ur"{greek} {gloss}; {gloss}, {text}$",
    ur"{greek} {gloss}; {gloss}; cp\. {greek}$",
    ur"{greek} {gloss}; {text} {gloss}, also {gloss}$",
    ur"{greek} {gloss}; {text}$",
    ur"{greek} {gloss}; {text}:{text}$",

    ur"{greek} {text}$",

    # equals

    ur"2 aor\. of {greek} {gloss}$",
    ur"=Attic {greek}$",
    ur"=earlier {greek}; {text}, then in past tenses {gloss}$",
    ur"=fem\. of {greek} {gloss}$",
    ur"=Hom\. {greek} {gloss}$",
    ur"=Macedonian {greek} {gloss}$",
    ur"=older {greek} /{greek}, fem\. of {greek}$",
    ur"=older {greek}$",
    ur"=older {greek}, {text}$",
    ur"={greek} {gloss}$",
    ur"={greek} {greek} τ\. {greek}$",
    ur"={greek} {greek}$",
    ur"={greek} {ref}$",
    ur"={greek} {see} {greek}$",
    ur"={greek} ’ {greek} {greek}$",
    ur"={greek} ’ {greek}$",
    ur"={greek} ’ {greek}; {gloss}$",
    ur"={greek}$",
    ur"={greek}, cp\. {greek} {gloss}; {gloss}$",
    ur"={greek}, fem\. of {greek}$",
    ur"=δι ’ ὅ$",
    ur"=ὁ {greek} {gloss}; {see} {greek}$",

    # other greek

    ur"Attic contracted form of {greek} {gloss}, perh\. Skt\. assoc\.$",
    ur"Attic contraction of {greek} {gloss}, Skt\. assoc\.$",
    ur"Attic for {greek}, cp\. {greek} and Lat\. {latin}$",
    ur"Attic form ={greek}, etym\. uncertain$",
    ur"Attic form of {greek}$",
    ur"Attic {greek}, etym\. unknown$",
    ur"Attic {greek}; {gloss}$",
    ur"based on the impv\. {greek} {gloss}$",
    ur"by- form of {greek} \({greek}, {greek} {gloss}\)$",
    ur"by- form of {greek} {gloss}$",
    ur"by- form of {greek}$",
    ur"by- form of {greek}; {gloss}$",
    ur"causal of {greek}$",
    ur"causal of {greek}; {greek} {gloss}$",
    ur"cogn\. w\. {greek} {gloss}$",
    ur"collateral form of {greek}$",
    ur"combination of {greek}, {greek}, {greek}, {greek}$",
    ur"common Gk\. name fr\. the adj\. {greek} {gloss}; {gloss}$",
    ur"comp\. of the adv\. {greek} {gloss}$",
    ur"comparative form of {greek}$",
    ur"comparative of {greek}$",
    ur"contr\. form of {greek}; cp\. Lat\. {latin}$",
    ur"contr\. of the epic form {greek} via Attic {greek}, the {greek}- forms being secondary$",
    ur"contracted from {greek} \(ἀ- priv\., {greek}\) {gloss}$",
    ur"contraction fr\. Homeric {greek}$",

    ur"\*{greek} {gloss}, cp\. {greek} {gloss}; the concept of doubling expressed in {greek} is associated with this verb$",
    ur"\*{greek} {half-gloss}$",
    ur"\*{greek}-, {greek} {gloss}$",
    ur"\={greek} {greek} {greek}$",
    ur"a common Gk\. name, derived in part fr\. the acc\. form of {greek}:{greek}$",
    ur"a connection w\. {greek} {gloss} is uncertain$",
    ur"a fixed form derived fr\. {greek} functioning as {text}$",
    ur"a formation developed from \*{greek} {greek} {gloss} and present in {greek} {greek}, hence the gen\. {greek} {greek} and associated inflection$",
    ur"a Hell\. form ={greek}$",
    ur"a hybrid formation fr\. \(ὁ\) {greek} {gloss} \+Lat\. {latin} \(hence Vulgate rendering {gloss}\)$",
    ur"a later formation:{greek}, {greek}$",
    ur"acc\. of {greek}, {greek}$",
    ur"according to legend, {greek}, a son of Zeus, founded the city of C\.$",
    ur"adv\. acc\. of {greek}$",
    ur"adv\. of {greek} \(cp\. prec\.\) {gloss} as in {text}$",
    ur"affirming particle, cp\. {greek} and Skt\. {skt}, intensive particle$",
    ur"akin to aor\. {greek} \({greek}\) which bears the sense {gloss}$",
    ur"akin to {greek} but the development is unclear$",
    ur"akin to {greek} {gloss} \({text}\) and {greek} {gloss}$",
    ur"akin to {greek} {gloss}$",
    ur"akin to {greek} {gloss}, e\. g\. {text}$",
    ur"akin to {greek} {gloss}; {gloss}$",
    ur"akin to {greek}$",
    ur"akin to {greek}; {gloss}, {text}$",
    ur"also {greek} {greek} {gloss}$",
    ur"also {greek} {greek}$",
    ur"also {greek}$",
    ur"also {greek}, {greek} in various mss\.$",
    ur"also {greek}- in some non- biblical mss\.$",
    ur"also {greek}; Heb\. {gloss}$",
    ur"alt\. form of {greek}$",
    ur"alternate form of {greek}$",
    ur"an alternate form of {greek}$",
    ur"an old form beside {greek}; {gloss}$",
    ur"apparently some assoc\. w\. {greek}$",
    ur"assoc\. w\. the prec\. {greek}- formations$",
    ur"assoc\. w\. {greek} {text}, pl\. as in {greek} {gloss}$",
    ur"assoc\. w\. {greek}; {gloss}, also {gloss}$",
    ur"assoc\. with {greek}, {text} \({gloss} and by metonymy {gloss} {text}\)$",
    ur"associated w\. the root of {greek} \({gloss} and {gloss}\), which in turn generates {greek}. S\. next\.$",
    ur"associated w\. {greek} {gloss}$",
    ur"associated w\. {greek}, the 2 pf\. of {greek}$",
    ur"association has been made principally with {greek} {gloss} {text}, and w\. {greek} \({greek}\) {gloss}$",
    ur"association with {greek} {gloss} is uncertain$",
    ur"cp\. \(τὸ\) {greek} {gloss}:etym\. unclear$",
    ur"cp\. \*{greek} {gloss}, {gloss}$",
    ur"cp\. Doric {greek} and Lat\. {latin}$",
    ur"cp\. epic noun {greek} and Attic {greek}, both {gloss}$",
    ur"cp\. epic verb {greek} {gloss}$",
    ur"cp\. epic {greek} {gloss}; {gloss}$",
    ur"cp\. Hom\. impv\. {greek} {gloss}$",
    ur"cp\. Hom\. {greek} /{greek} {gloss} {text}$",
    ur"cp\. Hom\. {greek} {gloss} in rank$",
    ur"cp\. Hom\. {greek} {gloss}$",
    ur"cp\. Hom\. {greek} {gloss}, also {greek} in sense {gloss}; {gloss}$",
    ur"cp\. Hom\. {greek} {greek} {gloss}$",
    ur"cp\. Hom\. {greek} {greek}$",
    ur"cp\. Homeric adv\. {greek} {gloss}$",
    ur"cp\. Homeric {greek} as {text}$",
    ur"cp\. Homeric {greek} {gloss}$",
    ur"cp\. the acc\. {greek} of \*{greek} {gloss} and {see} {greek}$",
    ur"cp\. the adj. {greek} {gloss}; {text}$",
    ur"cp\. the adv\. {greek}$",
    ur"cp\. the aor\. inf\. {greek} of {greek}; {text}, {gloss}, {text}, {gloss}$",
    ur"cp\. the aor\. {greek}; {gloss}$",
    ur"cp\. the earlier form {greek} {gloss}$",
    ur"cp\. the earlier {greek}$",
    ur"cp\. the element {greek}- in {greek}$",
    ur"cp\. the epic form {greek} {gloss}; rare in the nt\. form$",
    ur"cp\. the floral name {greek}$",
    ur"cp\. the formulation {greek} {greek}, {see} {greek} below$",
    ur"cp\. the fut\. and aor\. forms of {greek}$",
    ur"cp\. the Homeric pf\. {greek} and {see} {greek}$",
    ur"cp\. the name of the deity associated with festivity:{greek}$",
    ur"cp\. the poetic form {greek} and Hell\. {greek}, cp\. also Lat\. {latin} \(older form of {latin}/{latin}\)$",
    ur"cp\. the prec\. back- formation {greek}$",
    ur"cp\. the reduced form {pie} in {greek} {gloss}$",
    ur"cp\. the related term {greek} in sense of {text}$",
    ur"cp\. the suffix in {greek} {gloss}$",
    ur"cp\. the unused pres\. {greek} {gloss}$",
    ur"cp\. {greek} /{greek} {gloss} and {greek} {gloss}$",
    ur"cp\. {greek} 2 pf\. of {greek}$",
    ur"cp\. {greek} ={greek} {gloss}; prim\. {gloss}, {text}$",
    ur"cp\. {greek} \(2 pf\. of {greek}\) and {greek} \(dual form\) {gloss}$",
    ur"cp\. {greek} \(inf\. of an aor\. form {greek}\) {gloss}$",
    ur"cp\. {greek} \(marker of precedence\) and {greek} \(also {greek}\) {gloss}$",
    ur"cp\. {greek} \({greek}, {greek}\) {gloss}$",
    ur"cp\. {greek} \({greek}, {greek}\) {gloss}; {gloss}$",
    ur"cp\. {greek} \({text}\)$",
    ur"cp\. {greek} and Lat\. {latin} {gloss}$",
    ur"cp\. {greek} and Lat\. {latin}$",
    ur"cp\. {greek} and other {greek}- formations; the primary idea is one of {gloss}, then of {gloss} based on what seems good or impressive, with {gloss} as product$",
    ur"cp\. {greek} and prec\. {greek}- cognates$",
    ur"cp\. {greek} and related forms$",
    ur"cp\. {greek} and {greek} \(={gloss}\)$",
    ur"cp\. {greek} and {greek} in sense of {gloss}$",
    ur"cp\. {greek} and {greek}$",
    ur"cp\. {greek} and {greek}, and s\. {greek}$",
    ur"cp\. {greek} and {greek}, {greek}$",
    ur"cp\. {greek} in primary sense of {gloss}$",
    ur"cp\. {greek} in sense of {gloss} {text} ={gloss}; {see} {greek}$",
    ur"cp\. {greek} in sense of {gloss}$",
    ur"cp\. {greek} opp\. {greek}$",
    ur"cp\. {greek} the fut\. of {greek} {gloss}$",
    ur"cp\. {greek} {gloss} ={gloss}$",
    ur"cp\. {greek} {gloss} \({see} {greek}\) and Homeric {greek} \({text}\) {gloss}$",
    ur"cp\. {greek} {gloss} and associated terms such as {greek} {gloss}, {greek} {gloss}, {greek} {gloss}; {gloss}$",
    ur"cp\. {greek} {gloss} and Hom\. {greek} {gloss}$",
    ur"cp\. {greek} {gloss} and Lat\. {latin}$",
    ur"cp\. {greek} {gloss} and {greek} {gloss}$",
    ur"cp\. {greek} {gloss} and {greek} {gloss}; {text} {gloss}, {text} {gloss}$",
    ur"cp\. {greek} {gloss} and {greek} {gloss}; {text} {gloss}; cp\. Lat\. {latin}$",
    ur"cp\. {greek} {gloss} and {greek}$",
    ur"cp\. {greek} {gloss} and {see} {greek}$",
    ur"cp\. {greek} {gloss} as a {gloss} {text}, {text} {gloss} {text}; {greek} {text}$",
    ur"cp\. {greek} {gloss} in Persia$",
    ur"cp\. {greek} {gloss} {text}$",
    ur"cp\. {greek} {gloss} {text}; {gloss}, then {gloss}$",
    ur"cp\. {greek} {gloss}$",
    ur"cp\. {greek} {gloss}, and {see} next$",
    ur"cp\. {greek} {gloss}, {greek} {gloss}$",
    ur"cp\. {greek} {gloss}, {greek}$",
    ur"cp\. {greek} {gloss}, {text}$",
    ur"cp\. {greek} {gloss}, {text}; cp\. our {gloss} in ref\. to {text}$",
    ur"cp\. {greek} {gloss}, {text}; {gloss}$",
    ur"cp\. {greek} {gloss}; cp\. {greek} {gloss}; the underlying idea is {gloss}$",
    ur"cp\. {greek} {gloss}; fr\. the sense {gloss}$",
    ur"cp\. {greek} {gloss}; the form {greek} is late$",
    ur"cp\. {greek} {gloss}; {gloss}$",
    ur"cp\. {greek} {gloss}; {gloss}, then {gloss}$",
    ur"cp\. {greek} {gloss}; {see} {greek}, {greek}$",
    ur"cp\. {greek} {text}$",
    ur"cp\. {greek}$",
    ur"cp\. {greek}, an animal of the deer family, such as {gloss}, in popular etymology \(cp\. {greek} {gloss}\) associated with bright eyes$",
    ur"cp\. {greek}, an older form of {greek} {gloss}$",
    ur"cp\. {greek}, assoc\. w\. Skt\., {gloss}, such as {gloss}, {gloss}$",
    ur"cp\. {greek}, messenger of the gods$",
    ur"cp\. {greek}, s\. {greek}$",
    ur"cp\. {greek}, the fut\. of {greek}, and {see} {greek}$",
    ur"cp\. {greek}, which does duty as an aor\. for {greek} used only in the pres\.$",
    ur"cp\. {greek}, {greek} \(={greek}\); {text}$",
    ur"cp\. {greek}, {greek} {gloss} fr\. {greek}$",
    ur"cp\. {greek}, {greek} {gloss}, and {greek} {gloss}$",
    ur"cp\. {greek}, {greek}$",
    ur"cp\. {greek}, {greek}, and Lat\. {latin}, {latin} {gloss}$",
    ur"cp\. {greek}, {greek}:{greek}:{gloss}, then {gloss}; {gloss}$",
    ur"cp\. {greek}, ή, όν {gloss}$",
    ur"cp\. {greek}- in {greek}, q\. v\.$",
    ur"cp\. {greek}- {greek}, {greek}- {greek}, {greek} \({greek} \+- {greek}, like {greek}\) {gloss}$",
    ur"cp\. {greek}; a function- oriented rather than status- oriented term$",
    ur"cp\. {greek}; freq\. w\. dat\. {gloss}$",
    ur"cp\. {greek}; Lat\. {latin} {gloss}$",
    ur"cp\. {greek}; mostly in pl\. {gloss}$",
    ur"cp\. {greek}; primary sense {gloss}, {text}$",
    ur"cp\. {greek}; {gloss} {text}$",
    ur"cp\. {greek}; {gloss}$",
    ur"cp\. {greek}; {gloss}, then {text} {gloss}$",
    ur"cp\. {greek}; {gloss}, {gloss}$",
    ur"cp\. {greek}; {gloss}, {text}$",
    ur"cp\. {greek}; {greek} expresses {text}$",
    ur"cp\. Lat\. {latin} {gloss}; in the strict sense:{text}; the synonym {greek} in the strict sense refers to {gloss} or {gloss}, {text}. Usage in the NT is much more fluid.$",
    ur"dat\. of {greek} {gloss}$",
    ur"derivation uncertain; the transl\. {greek} {greek} may reflect folk etymology$",
    ur"derived fr\. the gen\. of {greek}; {gloss}$",
    ur"derived from {greek}, {text}$",
    ur"developed out of the aor\. form {greek}$",
    ur"develops from the pf\. of {greek} {gloss}:{greek} {gloss}, hence {gloss}$",
    ur"dim\. akin to {greek} {gloss} \(cp\. {greek} in same sense\), etym\. unknown$",
    ur"dim\. of {greek} {gloss}$",
    ur"dim\. of {greek} {gloss}, orig\. uncertain$",
    ur"dim\. of {greek} {gloss}, prob\. of Asiatic orig\.$",
    ur"dim\. of {greek}$",
    ur"dim\. of {greek}, derived fr\. its gen\.; {gloss}, with pejorative aspect$",
    ur"dim\. of {greek}, which is a dim\. of {greek}$",
    ur"dim\. of {greek}, whose orig\. is uncertain$",
    ur"dim\. of {greek}; {gloss} \({text}\), hence {gloss} {text} \({text}\) {text}$",
    ur"dim\. of {greek}; {gloss}$",
    ur"dim\. of {greek}; {text}$",
    ur"diminutive of {greek} {gloss} \({text}\); {gloss}, then by ext\. {gloss}$",
    ur"diminutive of {greek}; ordinarily {gloss}, but also {gloss}$",
    ur"Doric form of {greek}$",
    ur"Epic {greek} {gloss}$",
    ur"etym\. better sp\. {greek} fr\. Heb\. {gloss}$",
    ur"etym\. complex, but cp\. {greek} \({see} {greek}\)$",
    ur"etym\. complex, cp\. {greek} {gloss}$",
    ur"etym\. complex, cp\. {greek}$",
    ur"etym\. complex, cp\. {greek}; Lat\. {latin} {gloss} reflects {greek}$",
    ur"etym\. complex, perh\. a connection w\. {greek}; {text} {gloss}$",
    ur"etym\. complex, {greek} plays a role$",
    ur"etym\. in dispute \(note:no connection with {greek}\)$",
    ur"etym\. in question, some associate w\. {greek} {gloss}$",
    ur"etym\. not clear, but prob\. akin to {greek}; {gloss}$",
    ur"etym\. obscure, but cp\. {greek} {gloss} \(relating to ends of threads in a loom\)$",
    ur"etym\. uncertain but prob\. associated w\. {greek}$",
    ur"etym\. uncertain, cp\. {greek} {gloss}$",
    ur"etym\. uncertain, perh\. associated with {greek} in sense of {text}$",
    ur"etym\. uncertain; the translation {greek} {greek} {ref} may reflect popular etym\.$",
    ur"etym\. unclear \(many conflicting theories\), cp\. {greek} {gloss}$",
    ur"etym\. unclear, cp\. {greek}$",
    ur"etym\. unclear; the NT shows a preference for {greek}$",
    ur"etym\. unclear; {text}, in appearance like a {gloss}, the primary meaning of {greek}\.$",
    ur"fem\. acc\. of {greek}$",
    ur"fem\. counterpart of {greek}$",
    ur"fem\. of {greek}$",
    ur"fem\. pres\. pass\. ptc\. of {greek}, sc\. {greek}$",
    ur"folk- etymology \(ἀ- priv\., {greek} o {greek}\) underlies the Gk\. formation of this foreign word, suggesting perh\. {gloss}$",
    ur"folk- etymology \(ἀ- priv\., {greek}\) underlies the Gk\. formation of this foreign word, suggesting perh\. {gloss}$",
    ur"for older {greek}$",
    ur"for root {see} {greek}$",
    ur"for {greek} ’ {greek} ={greek} {greek}$",
    ur"for {greek}, 3 sg\. of {greek} {gloss}$",
    ur"for {greek}- cp\. the Hom\. aor\. {greek} \(fr\. an unused pres\. {greek} {gloss}\) {gloss}, {text}; for- {greek} cp\. {greek}$",
    ur"formally fem\. of {greek} {gloss}, cp\. Lat\. {latin}$",
    ur"formally the pres\. ptc\. of {greek}$",
    ur"formation of this {greek}- term uncertain$",
    ur"formed as the superl\. of the adv\. {greek} {gloss}$",
    ur"formed by crasis from {greek} \+{greek}$",
    ur"formed fr\. {greek} ’ {greek} \({greek} \+{greek}\)$",
    ur"formed in association w\. {greek}$",
    ur"fr\. \*{greek}- \(as in {greek}, {greek}\), {text}, plus- {greek} \(ν\) {text}$",
    ur"fr\. \*ὀπ- \(cp\. {greek}\) and \*ὀ \[σ$",
    ur"fr\. a noun \*{greek} {gloss}; {gloss}$",
    ur"fr\. a root related to Latvian {latvian} {gloss}, cp\. {greek}$",
    ur"fr\. a root related to Lithuanian {lithuanian} {gloss}, Attic form:{greek}; {gloss}, then {gloss} {text}$",
    ur"fr\. pron\. {greek} and source suffix- {greek}$",
    ur"fr\. the aor\. inf\. {greek} of {greek} {gloss}; freq\. ={greek}$",
    ur"fr\. the fut\. of {greek}, {greek}$",
    ur"fr\. the gen\. of an adj\. \*{greek} or its nominal form \*{greek} in ref\. to serial connection; cp\. {greek} {greek} {gloss}$",
    ur"fr\. {greek} and =Lat\. {latin} {gloss}$",
    ur"fr\. {greek}, ptc\. of {greek}$",
    ur"fr\. {greek}, the pres\. fem\. ptc\. of {greek}$",
    ur"fr\. {greek}, {text}$",
    ur"fr\. {text} {greek}$",
    ur"freq\. as v\. l\. for {greek}$",
    ur"freq\. Ἐ\.; Heb\. {gloss}$",
    ur"from an IE root signfiying {text}, {see} {greek}$",
    ur"from the adj\. {greek} {half-gloss}$",
    ur"from the var\. {greek} comes the customary rendering {gloss}$",
    ur"generally accepted as contraction of {greek} and {greek}:in a broad sense ={gloss}$",
    ur"Gk\. name \({greek}, {greek} {gloss}\)$",
    ur"Gk\. name \({greek}, {greek}\)$",
    ur"Gk\. name corresponding to {greek} \({greek}, {greek}\) {gloss}; {gloss}$",
    ur"Grecized form of Heb\. name \({see} {greek}\)$",
    ur"Heb\.; also found in the more correct form {greek}$",
    ur"heightened form of {greek} {gloss}$",
    ur"heightened form of {greek}$",
    ur"Hell\. form for {greek} \({greek}, {greek} {gloss}\)$",
    ur"Hell\. Gk\. for {greek} {gloss}$",
    ur"Hellenistic form of {greek} {gloss}$",
    ur"Hom\. {greek} {gloss}; cp\. Lat\. {latin}$",
    ur"I\. {greek}$",
    ur"IE pronominal stem {pie} \+suff\.- {greek}$",
    ur"IE {pie}, cp\. {greek} {gloss}$",
    ur"IE, acc\. of {greek} {gloss}$",
    ur"IE, assoc\. w\. {greek} in some forms but not in sense \({greek} relates to {text}\)$",
    ur"IE, cp\. {greek} {gloss}$",
    ur"IE, cp\. {greek} {gloss}, {greek} {gloss}$",
    ur"IE, cp\. {greek} {gloss}; {gloss}$",
    ur"IE, cp\. {greek}$",
    ur"IE, cp\. {greek}; {gloss}$",
    ur"IE; cp\. {greek}$",
    ur"IE; the pres\. of this verb gives way to {greek} and {greek}; there is no aor\. act\. form, inasmuch as {greek} established itself to express that aspect$",
    ur"impersonal verb 3 sg\. of the unused {greek}, cp\. {greek}$",
    ur"impersonal verb from {greek} {gloss}$",
    ur"in Hom\. {greek}$",
    ur"in older Gk\. also {greek}$",
    ur"intensified form of {greek}$",
    ur"intensive enclitic in some such sense as {gloss}, ={greek} {greek}$",
    ur"intensive of {greek}$",
    ur"Ionic and Hell\. form ={greek}, cp\. Lat\. {latin}; the central mng\. {gloss}$",
    ur"Ionic and later Gr\. for {greek} {gloss}$",
    ur"Ionic for {greek}, cp\. {greek}; in the pass\. usually {gloss}$",
    ur"Ionic {greek}, cp\. Hom\. {greek} and next entry$",
    ur"late adj\. from the adv\. {greek} {gloss}$",
    ur"late by- form of {greek}$",
    ur"late for {greek}$",
    ur"late form fr\. {greek}$",
    ur"late form of {greek} {gloss}$",
    ur"late form of {greek}$",
    ur"late form of {greek}, cp\. prec\.$",
    ur"late form of {greek}, fr\. {greek}$",
    ur"late formation, cp\. {greek}$",
    ur"later form for {greek}, {greek}$",
    ur"later form of {greek} ={greek}$",
    ur"later form of {greek} in same sense$",
    ur"later form of {greek}$",
    ur"later form of {greek}:{greek}, {greek} {gloss}$",
    ur"later form of {greek}:ἀ- priv\., {greek} {gloss}$",
    ur"later form of {greek}; etym\. unclear$",
    ur"later form of {greek}\. IE, cp\. {greek}$",
    ur"later sp\. of {greek}$",
    ur"later word for {greek} and freq\. w\. {greek} as v\. l\.$",
    ur"lengthened form of {greek}$",
    ur"mid\. of {greek} {gloss}, not {greek} {gloss}$",
    ur"more correctly {greek} {greek}, where {greek} =the asseverative {greek}$",
    ur"neg\. {greek}- and {greek} {gloss}$",
    ur"not to be confused with the homograph {greek} {gloss}, with which the impersonal {greek} is associated$",
    ur"noun dervied from the adj\. {greek} {gloss}$",
    ur"noun from the adj\. {greek}, cp\. {greek}$",
    ur"nt\. comp\. of {greek} {gloss}$",
    ur"nt\. noun fr\. the adj\. {greek}, {gloss}; {gloss}, then {gloss}$",
    ur"nt\. of {greek}$",
    ur"nt\. pl\. of {greek} {gloss}$",
    ur"of complex origin; cp\. Hom\. {greek} {greek} {gloss}$",
    ur"of same orig\. as {greek}$",
    ur"old pf\. of {greek}$",
    ur"onomatopoetic prefix, {greek}, cp\. {greek} {gloss} and Lat\. {latin}$",
    ur"opp\. Hom\. {greek} {gloss}$",
    ur"opp\. {greek} {gloss}$",
    ur"orig\. the nt\. of the rel\. pron\. {greek}$",
    ur"orig\. uncertain, akin to {greek}$",
    ur"orig\. uncertain, but cp\. {greek} {gloss}; {gloss}$",
    ur"orig\. uncertain, but {greek} appears to be a component$",
    ur"orig\. uncertain, cp\. {greek} {gloss}$",
    ur"orig\. uncertain; opp\. {greek}, {greek} {gloss}$",
    ur"orig\. unclear, cp\. {greek} {gloss}$",
    ur"orig\. undetermined, cp\. {greek} {gloss} and {see} prec\.$",
    ur"orig\. {greek}; prep\. w\. acc\.:{text}, {gloss}, {text}, {gloss}$",
    ur"parallel form of the nt\. {greek} {gloss}$",
    ur"perh\. a loanword from an area in Asia Minor; cp\. {greek}$",
    ur"perh\. akin to {greek} {gloss}$",
    ur"perh\. assoc\. w\. {greek}$",
    ur"perh\. short for {greek}$",
    ur"perh\. short form of {greek}$",
    ur"perh\. Skt\. assoc\., cp\. {greek} {gloss}$",
    ur"pf\. of an obsolete pres\. of {greek} {gloss} and with the force of the pres\. tense$",
    ur"pres\. tense derived from an aor\. {greek}$",
    ur"prob\. ={greek}, an endearing term like {greek}; {see} prec\.$",
    ur"proper name in form of a participle from {greek}$",
    ur"properly nt\. gen\. of {greek}$",
    ur"reduplicated {greek}$",
    ur"related to {greek} in its secondary sense of {text}, cp\. the Lat\. loanword {latin} in the same sense$",
    ur"related to {greek} {gloss}, which is a later form of {greek} w\. the same mng\.$",
    ur"related to {greek}$",
    ur"related to {greek}; {gloss}$",
    ur"short form of {greek} {gloss}$",
    ur"Skt. dádāmi, cp. {greek}$",
    ur"Skt\. assoc\. fem\. of the adj\. {greek}, ά, όν {gloss}$",
    ur"Skt\. assoc\., cp\. {greek} /{greek} /{greek} {gloss}; orig\. {gloss}, then {gloss}$",
    ur"Skt\. assoc\., cp\. {greek} and Lat\. {latin} {gloss}$",
    ur"Skt\. assoc\., cp\. {greek} {gloss} {text}$",
    ur"Skt\. assoc\., cp\. {greek} {gloss}$",
    ur"Skt\. assoc\., cp\. {greek} {gloss}; in Homer both as {gloss} and {gloss}$",
    ur"Skt\. assoc\., cp\. {greek}$",
    ur"Skt\. {skt} {gloss}, and akin to {greek}$",
    ur"Skt\., cp\. {greek}$",
    ur"Skt\.; cp\. {greek} {gloss}$",
    ur"so accented because it is really two words {greek}, {greek}$",
    ur"some relation to Skt\. is discernible. {text} {greek} {text}:1. {text}; 2. {text}; 3. {text}. {text} Cp\. Lat\. {latin} for 2 above\.$",
    ur"special naming use of {greek} {gloss}$",
    ur"strengthened form of {greek} {gloss}$",
    ur"strengthened form of {greek}$",
    ur"superl\. of the adv\. {greek} {gloss}$",
    ur"superl\. of {greek}$",
    ur"the affix {greek}- is common$",
    ur"the alt\. form– {greek} only in ptc\.$",
    ur"the Attic form, assoc\. with {greek} {gloss}$",
    ur"the form {greek} is freq\. in later Gk\.$",
    ur"the gen\. of {greek}$",
    ur"the history of association with the name of an eponymous ancestor {greek} {gloss} is complex$",
    ur"the Ionic form of {greek} q\. v\.$",
    ur"the more freq\. form of {greek} in earlier Gk\. lit\.; {gloss}$",
    ur"the nt\. rel\. ὅ and {greek}$",
    ur"the nt\. rel\. ὅ, {greek}$",
    ur"the suffix- {greek} suggests source$",
    ur"the superl\. of {greek}$",
    ur"used as 2 aor\. of {greek}$",
    ur"used as 2 aor\. of {greek}, which in turn serves in the pres\. tense for \*{greek}; late forms, such as {greek} al\., are often used in the NT$",
    ur"vernacular form of {greek}$",
    ur"via {greek}$",
    ur"w\. root in common w\. {greek}, {gloss}$",
    ur"{gloss}, the pass\. of the idea conveyed in {greek}$",
    # ur"{greek} /{greek} \(={text}\), {greek}$",
    # ur"{greek} /{greek} \({see} prec\.\), {greek} {gloss}$",
    # ur"{greek} /{greek} {gloss}$",
    # ur"{greek} /{greek} {gloss}, cp\. {greek} {gloss}$",
    # ur"{greek} /{greek} {gloss}, of Semitic orig\.; {gloss}, then {gloss}$",
    # ur"{greek} /{greek}$",
    # ur"{greek} ={greek} \({see} {greek}\), {greek}$",
    # ur"{greek} ={greek} {gloss}$",
    # ur"{greek} ={greek}$",
    # ur"{greek} \(- {greek} derives fr\. the pf\. mid\. {greek}\)$",
    # ur"{greek} \(={greek}\); {gloss}$",
    # ur"{greek} \(aor\. of {greek}\)$",
    # ur"{greek} \(cp\. Engl\. use of {gloss} in ref\. to {text}\)$",
    # ur"{greek} \(cp\. epic {greek} {gloss}\) {gloss}, {text}$",
    # ur"{greek} \(functions with the sense {gloss}\), {greek}$",
    # ur"{greek} \(intensive\), {greek}; {gloss}$",
    # ur"{greek} \(mostly pl\. {greek} the people from whom silk was obtained\)$",
    # ur"{greek} \(nt\. of {greek}\), {greek}$",
    # ur"{greek} \(reduplicated form of {greek}\)$",
    # ur"{greek} \(s\. {greek}\), cp\. {greek}$",
    # ur"{greek} \(w\. focus on separation\), {greek} {gloss}, freq\. with connotation of {text}$",
    # ur"{greek} \({gloss} and {gloss}\) via {greek}$",
    # ur"{greek} \({greek} \+\*{greek} fr\. \*{greek} {gloss}\) {gloss}; cp\. {greek} {gloss}$",
    # ur"{greek} \({greek} and {greek} via the aor\. pass\. inf\. {greek}\)$",
    # ur"{greek} \({greek} and {greek}, {see} {greek}\) {gloss}$",
    # ur"{greek} \({greek} {gloss}, {greek} {gloss}\) {gloss}$",
    # ur"{greek} \({greek} {gloss}, {greek}\) {gloss}$",
    # ur"{greek} \({greek}, {greek} /{greek}\) {gloss}$",
    # ur"{greek} \({greek}, {greek} {gloss}, {greek}\) {gloss}$",
    # ur"{greek} \({greek}, {greek} {gloss}\) {gloss}$",
    # ur"{greek} \({greek}, {greek} {gloss}\) {gloss}, {text}; {gloss}$",
    # ur"{greek} \({greek}, {greek} {gloss}\)$",
    # ur"{greek} \({greek}, {greek}\) {gloss} \({text} {greek}\)$",
    # ur"{greek} \({greek}, {greek}\) {gloss}$",
    # ur"{greek} \({greek}, {greek}\) {gloss}, {text}$",
    # ur"{greek} \({greek}, {greek}\) {gloss}; {gloss}$",
    # ur"{greek} \({greek}, {greek}\)$",
    # ur"{greek} \({greek}, {greek}\), pass\. {gloss}$",
    # ur"{greek} \({greek}, {text}\) {gloss}$",
    # ur"{greek} \({greek}-, {greek}\) cp\. {greek} {gloss}$",
    # ur"{greek} \({greek}\) tr\. {gloss}, intr\. {gloss}$",
    # ur"{greek} \({greek}\) {gloss} fr\. {greek}$",
    # ur"{greek} \({greek}\) {gloss} via its lengthened form {greek} in same sense$",
    # ur"{greek} \({greek}\) {gloss}$",
    # ur"{greek} \({greek}\) {gloss}, {greek}$",
    # ur"{greek} \({greek}\) {greek}$",
    # ur"{greek} \({see} {greek}\)$",
    # ur"{greek} \({text}\), {greek}, {greek}$",
    # ur"{greek} \(ἀ- priv\., {greek} o {greek}\) {gloss}$",
    # ur"{greek} \(ἀ- priv\., {greek} {half-gloss}\) {gloss}$",
    # ur"{greek} \(ἀ- priv\., {greek}\) {gloss}$",
    # ur"{greek} \(ἀ- priv\., {greek}\) {gloss}, fr\. {greek}$",
    # ur"{greek} \(ἀ- priv\., {greek}\); {gloss} i\. e\. {gloss}$",
    # ur"{greek} \+- {greek} formed fr\. the pres\. act\. ptc\. of {greek}$",
    # ur"{greek} \+- {greek} {text}$",
    # ur"{greek} \+- {greek}$",
    # ur"{greek} \+- {greek}, of complex derivation$",
    # ur"{greek} \+- {greek}, {greek}, {greek}; {text}$",
    # ur"{greek} \+a root with focus on independent action; {gloss}$",
    # ur"{greek} \+formation underlying e\. g\. {greek}$",
    # ur"{greek} \+{greek}$",
    # ur"{greek} adv\. {gloss}$",
    # ur"{greek} Aeolic form of {greek}$",
    # ur"{greek} and assoc\. w\. {greek} in sense of {gloss}$",
    # ur"{greek} and forms of {greek}; {gloss}$",
    # ur"{greek} and indefinite {greek}; {greek} {greek} is also written {greek}, {greek} and {greek}$",
    # ur"{greek} and {greek} via {greek} {gloss} \({text}\)$",
    # ur"{greek} as collective {gloss}$",
    # ur"{greek} fr\. {greek}$",
    # ur"{greek} fr\. {greek}; {gloss}, hence {gloss}$",
    # ur"{greek} gener\. ={gloss}$",
    # ur"{greek} in sense of {gloss}, {greek}$",
    # ur"{greek} in sense of {gloss}; {gloss}$",
    # ur"{greek} Ionic form of {greek} q\. v\.$",
    # ur"{greek} Ionic form of {greek}$",
    # ur"{greek} is intensive; {gloss} ={text}$",
    # ur"{greek} late form of {greek}, cp\. prec\.$",
    # ur"{greek} late form of {greek}, cp\. {greek} \(ε\) {greek}$",
    # ur"{greek} late form of {greek}, fr\. {greek} {gloss}, also {gloss}$",
    # ur"{greek} o ς, {greek} {gloss}$",
    # ur"{greek} ordinarily in the sense {gloss}$",
    # ur"{greek} reinforced by {greek} in sense of {gloss}$",
    # ur"{greek} strengthened with demonstrative suffix- ι$",
    # ur"{greek} via an IE root assoc\. w\. {greek} {gloss}$",
    # ur"{greek} via aor\. form {greek}$",
    # ur"{greek} via its gen\. {greek} \({text}\)$",
    # ur"{greek} via the nt\. {greek}$",
    # ur"{greek} via the perf\. {greek}$",
    # ur"{greek} via the pf\. {greek}$",
    # ur"{greek} via {greek} {gloss} \(e\. g\. {text}\)$",
    # ur"{greek} via {greek} {gloss}$",
    # ur"{greek} via {greek}$",
    # ur"{greek} w\. distibutive force, {greek}$",
    # ur"{greek} with connotation of {gloss}, {greek}$",
    # ur"{greek} with intensive force {greek}; {gloss}$",
    # ur"{greek} with its full force, {greek} {gloss}$",
    # ur"{greek} with perfective force, {greek}$",
    # ur"{greek} {gloss} \(e\. g\. the mouth\); {gloss}$",
    # ur"{greek} {gloss} \(noun\) via {greek} {gloss} \(adj\.\)$",
    # ur"{greek} {gloss} \({greek}, {greek}\)$",
    # ur"{greek} {gloss} \({greek}, {greek}\); {gloss}$",
    # ur"{greek} {gloss} \({see} {greek}\) \+- {greek} \(cp\. {greek} {gloss}\)$",
    # ur"{greek} {gloss} \+- {greek}; cp\. {greek}$",
    # ur"{greek} {gloss} fr\. an older ptc\. form and and connected with {greek}$",
    # ur"{greek} {gloss} fr\. {greek} a later form of {greek}$",
    # ur"{greek} {gloss} fr\. {greek} and {greek}$",
    # ur"{greek} {gloss} fr\. {greek} in sense of {text}$",
    # ur"{greek} {gloss} fr\. {greek}$",
    # ur"{greek} {gloss} fr\. {greek}, {greek}$",
    # ur"{greek} {gloss} or {gloss}$",
    # ur"{greek} {gloss} or {gloss}; {gloss}, then by ext\. {gloss}$",
    # ur"{greek} {gloss} then also {gloss}, fr\. {greek}, {greek}$",
    # ur"{greek} {gloss} then {gloss}$",
    # ur"{greek} {gloss} via {greek} {gloss}$",
    # ur"{greek} {gloss} via {greek} {gloss}, cp\. {greek} {gloss}$",
    # ur"{greek} {gloss} via {greek}$",
    # ur"{greek} {gloss} via {greek}; {gloss}$",
    # ur"{greek} {gloss} via ὁ {greek} {gloss}, {text}$",
    # ur"{greek} {gloss} {text}$",
    # ur"{greek} {gloss} {text}$",
    # ur"{greek} {gloss} {text}:to be {greek} \(ἀ- priv\.\) means that one {text}; {gloss}$",
    # ur"{greek} {gloss}$",
    # ur"{greek} {gloss}, also {gloss}$",
    # ur"{greek} {gloss}, also {gloss}, cp\. {greek} {gloss}$",
    # ur"{greek} {gloss}, also {gloss}, pre- Gk\.$",
    # ur"{greek} {gloss}, cp\. Hom\. {greek} {gloss}$",
    # ur"{greek} {gloss}, cp\. its 2 aor\. {greek}$",
    # ur"{greek} {gloss}, cp\. Lat\. {latin} {gloss}$",
    # ur"{greek} {gloss}, cp\. the corresponding nt\. {greek}$",
    # ur"{greek} {gloss}, cp\. the pf\. {greek}$",
    # ur"{greek} {gloss}, cp\. {greek} above$",
    # ur"{greek} {gloss}, cp\. {greek} {gloss} and {greek}$",
    # ur"{greek} {gloss}, cp\. {greek} {gloss}$",
    # ur"{greek} {gloss}, cp\. {greek} {gloss}; in sense ranging from {gloss} to {gloss}$",
    # ur"{greek} {gloss}, cp\. {greek} {gloss}; {gloss}$",
    # ur"{greek} {gloss}, cp\. {greek}$",
    # ur"{greek} {gloss}, cp\. {greek}, {greek} {gloss}$",
    # ur"{greek} {gloss}, cp\. {greek}; {gloss} in var\. senses, including {text}$",
    # ur"{greek} {gloss}, cp\. {greek}; {gloss}, thus effecting {gloss}$",
    # ur"{greek} {gloss}, fr\. {greek} {gloss} in composition w\. {greek} {gloss}$",
    # ur"{greek} {gloss}, from which {greek} is derived; cp\. {greek}$",
    # ur"{greek} {gloss}, mid\. {gloss}$",
    # ur"{greek} {gloss}, not to be confused with the homograph {greek} {gloss}$",
    # ur"{greek} {gloss}, the prefix {greek} emphasizes {text}$",
    # ur"{greek} {gloss}, then also as nautical term {gloss} because {text}$",
    # ur"{greek} {gloss}, then in transf\. sense {gloss} and so a {gloss}$",
    # ur"{greek} {gloss}, then {gloss} {text}$",
    # ur"{greek} {gloss}, then {greek}, {text}$",
    # ur"{greek} {gloss}, then {text} {gloss}, cp\. our colloquial {gloss}; {gloss}$",
    # ur"{greek} {gloss}, {greek} \(reduplicated\)$",
    # ur"{greek} {gloss}, {greek} via {greek}$",
    # ur"{greek} {gloss}, {greek} {gloss} and cp\. {greek} {gloss}; {gloss}$",
    # ur"{greek} {gloss}, {greek} {gloss} fr\. {greek}$",
    # ur"{greek} {gloss}, {greek} {gloss} {text} {greek} {gloss}$",
    # ur"{greek} {gloss}, {greek} {gloss}$",
    # ur"{greek} {gloss}, {greek} {gloss}; {gloss}$",
    # ur"{greek} {gloss}, {greek} {gloss}; {text}$",
    # ur"{greek} {gloss}, {greek}$",
    # ur"{greek} {gloss}, {greek}; as noun fr\. the adj\. {greek} s {gloss}$",
    # ur"{greek} {gloss}, {greek}; predominantly appearing in the contracted form {greek}$",
    # ur"{greek} {gloss}, {greek}; {gloss} \({see} {greek}\)$",
    # ur"{greek} {gloss}, {greek}; {gloss}$",
    # ur"{greek} {gloss}, {greek}; {gloss}, {text}$",
    # ur"{greek} {gloss}, {greek}; {text}$",
    # ur"{greek} {gloss}, {see} {greek}$",
    # ur"{greek} {gloss}, {text}$",
    # ur"{greek} {gloss},- {greek} \(suffix signifying {text}\)$",
    # ur"{greek} {gloss},- {greek} signifying place whither$",
    # ur"{greek}, \*{greek}$",
    # ur"{greek}, a city in Transjordania$",
    # ur"{greek}, a poetic term ={greek}$",
    # ur"{greek}, addition of {greek} indicates {text}$",
    # ur"{greek}, also {greek}$",
    # ur"{greek}, an adj\. {gloss}, {text} \({text}\) \+{greek} \({greek}\) {gloss} \(hence {gloss}\)$",
    # ur"{greek}, an older form not found in NT, and {greek}; prob\. formed in Christian circles$",
    # ur"{greek}, and akin to {greek} {gloss}$",
    # ur"{greek}, and cp\. {greek}$",
    # ur"{greek}, and for- {greek} cp\. {greek} and {greek}$",
    # ur"{greek}, and the adj\. {greek} {gloss} then gener\. {gloss}$",
    # ur"{greek}, cp\. aor\. pass\. of {greek}:{greek}$",
    # ur"{greek}, cp\. the fut\. {greek}$",
    # ur"{greek}, cp\. the pf\. {greek}$",
    # ur"{greek}, cp\. {greek} \({greek}, {greek}\) {gloss}$",
    # ur"{greek}, cp\. {greek} and {greek} in sense of {gloss}$",
    # ur"{greek}, cp\. {greek} {gloss}",
    # ur"{greek}, cp\. {greek} {text}$",
    # ur"{greek}, cp\. {greek}$",
    # ur"{greek}, cp\. {greek}, {greek}$",
    # ur"{greek}, cp\. {greek}; ={greek}, which is preferred in later Gk\.$",
    # ur"{greek}, cp\. {greek}; {gloss}$",
    # ur"{greek}, enclitic {greek}$",
    # ur"{greek}, for- {greek} cp\. {greek} {gloss}$",
    # ur"{greek}, founder of {greek}\.$",
    # ur"{greek}, Gk\. deity$",
    # ur"{greek}, in early Gk. {gloss}$",
    # ur"{greek}, loanword in Lat\. {latin} \(based on the alt\. form {greek}\) {gloss}, weather- proofed$",
    # ur"{greek}, originally nt\. pl\. of {greek} with change in accent reflecting emphasis {gloss}; stronger than {greek}$",
    # ur"{greek}, the term for {text} in Hittite and Egyptian texts and Homer$",
    # ur"{greek}, via the fut\. {greek}$",
    # ur"{greek}, which s\. for details; in older Gk\. {gloss}, as well as {gloss}$",
    # ur"{greek}, {gloss}$",
    # ur"{greek}, {greek} /{greek} {gloss}, hence {greek} signifies close of pregnancy$",
    # ur"{greek}, {greek} /{greek}$",
    # ur"{greek}, {greek} ={greek} {gloss} {text}$",
    # ur"{greek}, {greek} ={greek} {gloss}$",
    # ur"{greek}, {greek} ={greek}, both in sense of {gloss}$",
    # ur"{greek}, {greek} \(2 aor\. inf\. of {greek}\)$",
    # ur"{greek}, {greek} \(2 aor\. of {greek}\) via {greek}$",
    # ur"{greek}, {greek} \(={greek}\), {gloss}, {text}$",
    # ur"{greek}, {greek} \(a rare word associated w\. {greek} {gloss}\)$",
    # ur"{greek}, {greek} \(Attic for {greek}\)$",
    # ur"{greek}, {greek} \(causal of {greek} {gloss}\) {gloss}$",
    # ur"{greek}, {greek} \(cp\. 2 aor\. {greek}\)$",
    # ur"{greek}, {greek} \(cp\. the aor\. inf\. {greek}\)$",
    # ur"{greek}, {greek} \(cp\. the epic form {greek}\); {gloss}$",
    # ur"{greek}, {greek} \(cp\. {greek} and {greek} the aor\. and pf\. forms of {greek}\) {gloss}$",
    # ur"{greek}, {greek} \(cp\. {greek}\)$",
    # ur"{greek}, {greek} \(Doric form of {greek}\)$",
    # ur"{greek}, {greek} \(epic form of {greek} /{greek}\) cp\. {greek} {gloss}$",
    # ur"{greek}, {greek} \(formed like {greek}\)$",
    # ur"{greek}, {greek} \(fr\. {greek} {gloss}\); {gloss}$",
    # ur"{greek}, {greek} \(in sense of {text}, cp\. {greek}, {greek} {gloss}\)$",
    # ur"{greek}, {greek} \(intensifying enclitic particle\)$",
    # ur"{greek}, {greek} \(mid\. of {greek} {gloss}\)$",
    # ur"{greek}, {greek} \(no present in use\)$",
    # ur"{greek}, {greek} \({gloss}, such as a {gloss}, {text}:{gloss} ={greek}\) fr\. {greek}$",
    # ur"{greek}, {greek} \({gloss}\); {gloss}, then {gloss}$",
    # ur"{greek}, {greek} \({greek} \+{greek}\) {gloss} fr\. {greek}; {gloss}$",
    # ur"{greek}, {greek} \({greek} {gloss}, {greek}\) {gloss}$",
    # ur"{greek}, {greek} \({greek} {gloss}\) {gloss}$",
    # ur"{greek}, {greek} \({greek} {gloss}\)$",
    # ur"{greek}, {greek} \({greek}, {greek} {gloss} {text}\) {gloss} {text}$",
    # ur"{greek}, {greek} \({greek}, {greek}\) {gloss}$",
    # ur"{greek}, {greek} \({greek}\) {gloss}$",
    # ur"{greek}, {greek} \({greek}\)$",
    # ur"{greek}, {greek} \+- {greek}, as prep\. and adv\. {gloss}$",
    # ur"{greek}, {greek} and cp\. {greek}$",
    # ur"{greek}, {greek} and cp\. {greek}; {gloss}$",
    # ur"{greek}, {greek} cp\. {greek} {gloss}$",
    # ur"{greek}, {greek} cp\. {greek}$",
    # ur"{greek}, {greek} esp\. {text}$",
    # ur"{greek}, {greek} fr\. {greek} \({greek}\) {gloss}$",
    # ur"{greek}, {greek} fr\. {greek} {gloss}, cp\. {greek} {gloss}$",
    # ur"{greek}, {greek} fr\. {greek} {gloss}; intr\. {gloss}$",
    # ur"{greek}, {greek} fr\. {greek}$",
    # ur"{greek}, {greek} fr\. {greek}, cp\. {greek} {gloss}$",
    # ur"{greek}, {greek} fr\. {greek}, cp\. {greek} {gloss}; {gloss}$",
    # ur"{greek}, {greek} fr\. {greek}, cp\. {greek}$",
    # ur"{greek}, {greek} fr\. {greek}; in later Gk\. {greek} gives way to {greek}$",
    # ur"{greek}, {greek} fr\. {greek}; {gloss}$",
    # ur"{greek}, {greek} fr\. {greek}; {gloss}, hence {gloss}$",
    # ur"{greek}, {greek} in primary sense of {gloss}$",
    # ur"{greek}, {greek} in sense of {gloss} \({gloss}\)$",
    # ur"{greek}, {greek} in sense of {gloss}$",
    # ur"{greek}, {greek} primary sense {gloss}, fr\. {greek}; {gloss}, then {gloss}$",
    # ur"{greek}, {greek} reinforcing particle {gloss}$",
    # ur"{greek}, {greek} the mid\. of {greek} {gloss} in the sense of {gloss}$",
    # ur"{greek}, {greek} the pass\. of {greek}; {gloss}$",
    # ur"{greek}, {greek} used in the sense {gloss}, cp\. the 3 sg\. {greek}$",
    # ur"{greek}, {greek} via 2 aor\. {greek}$",
    # ur"{greek}, {greek} via its nt\. pl\.$",
    # ur"{greek}, {greek} via the mid\.$",
    # ur"{greek}, {greek} via the nt\.$",
    # ur"{greek}, {greek} via {greek} {gloss}$",
    # ur"{greek}, {greek} via {greek} {gloss}, in various senses, including {text} as {gloss} and {gloss}$",
    # ur"{greek}, {greek} via {greek}$",
    # ur"{greek}, {greek} via {greek}; the prefix, apparently redundant, makes the idea of {text} in {greek} explicit$",
    # ur"{greek}, {greek} via {greek}; {gloss}$",
    # ur"{greek}, {greek} {gloss} ={text} {greek}$",
    # ur"{greek}, {greek} {gloss} \(cp\. {greek} {gloss} and see {greek}\)$",
    # ur"{greek}, {greek} {gloss} \(cp\. {greek}\)$",
    # ur"{greek}, {greek} {gloss} \({greek} {gloss}\)$",
    # ur"{greek}, {greek} {gloss} \({text}\) fr\. {greek}$",
    # ur"{greek}, {greek} {gloss} also {gloss}, as compound fr\. {greek}$",
    # ur"{greek}, {greek} {gloss} as in {text}$",
    # ur"{greek}, {greek} {gloss} cp\. {greek} {text}$",
    # ur"{greek}, {greek} {gloss} cp\. {greek}$",
    # ur"{greek}, {greek} {gloss} formed from the fut\. of {greek}, the compound fr\. {greek}$",
    # ur"{greek}, {greek} {gloss} fr\. the mid\. of {greek}; {gloss}$",
    # ur"{greek}, {greek} {gloss} fr\. {greek} {gloss}$",
    # ur"{greek}, {greek} {gloss} fr\. {greek} {gloss}, and then w\. full force of {greek} in {greek} {gloss}$",
    # ur"{greek}, {greek} {gloss} fr\. {greek}$",
    # ur"{greek}, {greek} {gloss} fr\. {greek}, cp\. {greek} {gloss}$",
    # ur"{greek}, {greek} {gloss} fr\. {greek}, {greek} {gloss}$",
    # ur"{greek}, {greek} {gloss} fr\. {greek}; {gloss}$",
    # ur"{greek}, {greek} {gloss} in sense of {gloss}$",
    # ur"{greek}, {greek} {gloss} or {gloss}$",
    # ur"{greek}, {greek} {gloss} then {gloss}$",
    # ur"{greek}, {greek} {gloss} then {text} {gloss}$",
    # ur"{greek}, {greek} {gloss} via {greek} {gloss}$",
    # ur"{greek}, {greek} {gloss} via {greek}$",
    # ur"{greek}, {greek} {gloss} {text} fr\. {greek} {gloss}; {greek} has the force of {gloss}, i\. e\. {text}$",
    # ur"{greek}, {greek} {gloss} {text}$",
    # ur"{greek}, {greek} {gloss} {text}; {gloss} {text} {gloss}$",
    # ur"{greek}, {greek} {gloss} {text}’; {greek} emphasizes {text}$",
    # ur"{greek}, {greek} {gloss}$",
    # ur"{greek}, {greek} {gloss}, also {gloss}$",
    # ur"{greek}, {greek} {gloss}, as compound fr\. {greek}$",
    # ur"{greek}, {greek} {gloss}, cp\. {greek} {gloss}$",
    # ur"{greek}, {greek} {gloss}, cp\. {greek} {gloss}; the adj\. signifies {gloss}$",
    # ur"{greek}, {greek} {gloss}, cp\. {greek}$",
    # ur"{greek}, {greek} {gloss}, cp\. {greek}; {gloss}$",
    # ur"{greek}, {greek} {gloss}, cp\. {greek}; {gloss}, hence {gloss}$",
    # ur"{greek}, {greek} {gloss}, cp\. {greek}; {gloss}, mid\. {gloss}$",
    # ur"{greek}, {greek} {gloss}, cp\. {greek}; {text}$",
    # ur"{greek}, {greek} {gloss}, from the idea of {gloss} derives the sense {gloss} in ref\. to character$",
    # ur"{greek}, {greek} {gloss}, mid\. {gloss}$",
    # ur"{greek}, {greek} {gloss}, the basic idea of {greek} is {text}; the prep\. generally functions spatially {gloss}$",
    # ur"{greek}, {greek} {gloss}, {text}$",
    # ur"{greek}, {greek} {gloss}, {text}; {gloss}, or {gloss} {text}$",
    # ur"{greek}, {greek} {gloss}, {text}; {gloss}, then {gloss}$",
    # ur"{greek}, {greek} {gloss}; Hom\. {gloss}, then {gloss}$",
    # ur"{greek}, {greek} {gloss}; intensive form {half-gloss}$",
    # ur"{greek}, {greek} {gloss}; prim\. {gloss}, {text}$",
    # ur"{greek}, {greek} {gloss}; {gloss} {text}$",
    # ur"{greek}, {greek} {gloss}; {gloss}$",
    # ur"{greek}, {greek} {gloss}; {gloss}, hence {text}$",
    # ur"{greek}, {greek} {gloss}; {gloss}, then of containers for other objects such as money$",
    # ur"{greek}, {greek} {gloss}; {gloss}, then {gloss} \(cp\. our use of {gloss} in ref\. to {text}\)$",
    # ur"{greek}, {greek} {gloss}; {gloss}, then {gloss}$",
    # ur"{greek}, {greek} {gloss}; {gloss}, {text}$",
    # ur"{greek}, {greek} {greek} {greek}$",
    # ur"{greek}, {greek} {text} ={gloss}$",
    # ur"{greek}, {greek} {text}, cp\. {greek}$",
    # ur"{greek}, {greek}$",
    # ur"{greek}, {greek}, =older {greek} {gloss}$",
    # ur"{greek}, {greek}, cp\. the {greek}- formations$",
    # ur"{greek}, {greek}, cp\. {greek} and {greek} {gloss}$",
    # ur"{greek}, {greek}, cp\. {greek} and {greek}$",
    # ur"{greek}, {greek}, cp\. {greek} and {see} {greek}; {gloss}$",
    # ur"{greek}, {greek}, cp\. {greek} {gloss}$",
    # ur"{greek}, {greek}, cp\. {greek} {gloss}; {gloss}, also {gloss}$",
    # ur"{greek}, {greek}, cp\. {greek}$",
    # ur"{greek}, {greek}, cp\. {greek}- formations$",
    # ur"{greek}, {greek}, cp\. {greek}; tr\. {gloss}, intr\. {gloss}$",
    # ur"{greek}, {greek}, cp\. {greek}; {gloss}$",
    # ur"{greek}, {greek}, cp\. {greek}; {gloss}, then {gloss}, {text} {gloss}$",
    # ur"{greek}, {greek}, fr\. {greek}$",
    # ur"{greek}, {greek}, only in fut\. and aor\. {gloss}$",
    # ur"{greek}, {greek}, s\. {greek}$",
    # ur"{greek}, {greek}, via {greek} {gloss}$",
    # ur"{greek}, {greek}, {greek} \(intensifying enclitic particle\)$",
    # ur"{greek}, {greek}, {greek} {gloss}$",
    # ur"{greek}, {greek}, {greek}$",
    # ur"{greek}, {greek}, {greek}; {gloss}$",
    # ur"{greek}, {greek}, {greek}; {greek} {text}$",
    # ur"{greek}, {greek}, {see} next$",
    # ur"{greek}, {greek}, {text}, as in {greek}, cp\. Hom\. \*{greek} \(only in dat\.\) {gloss}, and {see} {greek}, as well as {greek}$",
    # ur"{greek}, {greek}:{greek} functions intensively; {gloss}$",
    # ur"{greek}, {greek}:{greek} {gloss}; {gloss}$",
    # ur"{greek}, {greek}; ={greek}$",
    # ur"{greek}, {greek}; act\. {gloss}, mid\. {gloss} {text}$",
    # ur"{greek}, {greek}; an anachronistic uncontracted form in the Nestle text for {greek}$",
    # ur"{greek}, {greek}; for older {greek}$",
    # ur"{greek}, {greek}; in non- biblical Gk\. {greek} in this word signifies {gloss}; {gloss} ={gloss}$",
    # ur"{greek}, {greek}; orig\. {gloss} {text}$",
    # ur"{greek}, {greek}; prim\. a commercial term$",
    # ur"{greek}, {greek}; prim\. {gloss} then {gloss}, {text}$",
    # ur"{greek}, {greek}; rare:{text} {gloss}$",
    # ur"{greek}, {greek}; rarely found for the older {greek}$",
    # ur"{greek}, {greek}; the idea of separation is strong in var\. senses including the act\. {gloss}, and the mid\. {gloss}, which implies a {greek} or {gloss} out of \({greek}\) a number of possibilities$",
    # ur"{greek}, {greek}; the mid\.:{gloss}$",
    # ur"{greek}, {greek}; the mng\. {gloss} is not used in the NT$",
    # ur"{greek}, {greek}; the noun is more freq\. than the adj\. {greek}, {greek}$",
    # ur"{greek}, {greek}; this 2 aor\. form is commonly used for the aor\. of {greek}$",
    # ur"{greek}, {greek}; this form, the nt\. of {greek}, which is used only in the nt\., signifies {gloss}$",
    # ur"{greek}, {greek}; tr\. {gloss}, intr\. {gloss}$",
    # ur"{greek}, {greek}; various senses in non- bibl\. Gk\.$",
    # ur"{greek}, {greek}; {gloss} ={gloss}, {text}$",
    # ur"{greek}, {greek}; {gloss} ={greek} {gloss}$",
    # ur"{greek}, {greek}; {gloss} also {gloss}$",
    # ur"{greek}, {greek}; {gloss} and so {gloss} on a specific object$",
    # ur"{greek}, {greek}; {gloss} and so {gloss}$",
    # ur"{greek}, {greek}; {gloss} esp\. {text}; {text}$",
    # ur"{greek}, {greek}; {gloss} i\. e\. {gloss}$",
    # ur"{greek}, {greek}; {gloss} opp\. {greek}$",
    # ur"{greek}, {greek}; {gloss} or {gloss}$",
    # ur"{greek}, {greek}; {gloss} {text}$",
    # ur"{greek}, {greek}; {gloss}$",
    # ur"{greek}, {greek}; {gloss}, but most freq\. in hostile sense, e\. g\. {gloss}$",
    # ur"{greek}, {greek}; {gloss}, e\. g\. {text}$",
    # ur"{greek}, {greek}; {gloss}, e\. g\. {text}, and therefore {gloss} {text} {gloss}$",
    # ur"{greek}, {greek}; {gloss}, hence {gloss}$",
    # ur"{greek}, {greek}; {gloss}, then by extension {gloss}$",
    # ur"{greek}, {greek}; {gloss}, then {gloss}$",
    # ur"{greek}, {greek}; {gloss}, then {gloss}, {text}$",
    # ur"{greek}, {greek}; {gloss}, then {text}$",
    # ur"{greek}, {greek}; {gloss}, {text}$",
    # ur"{greek}, {greek}; {gloss}:{text} {gloss} {text}$",
    # ur"{greek}, {greek}; {gloss}:{text}$",
    # ur"{greek}, {greek}; {gloss}; cp\. {greek}$",
    # ur"{greek}, {greek}; {gloss}; in description of two- edged weapons the extended use of δ\. suggests a devouring maw$",
    # ur"{greek}, {greek}; {greek} expresses the opposite of {greek} {gloss} and focuses on separation, with such senses as {gloss}; mod\. Gk\. {gloss} from a position$",
    # ur"{greek}, {greek}; {greek} functions in the sense of {gloss} or {gloss}$",
    # ur"{greek}, {greek}; {greek} {greek} ={gloss}, states Hesychius$",
    # ur"{greek}, {greek}; {greek} {text}$",
    # ur"{greek}, {greek}; {see} {greek}; {greek} suggests {text}$",
    # ur"{greek}, {greek}; {text} is {greek} {gloss}$",
    # ur"{greek}, {greek}; {text} {gloss}$",
    # ur"{greek}, {greek}; {text} {gloss}, hence {gloss} and so {gloss}$",
    # ur"{greek}, {greek}; {text} {gloss}, {text} {gloss}$",
    # ur"{greek}, {greek}; {text} {gloss}, {text} {greek}$",
    # ur"{greek}, {greek}; {text}$",
    # ur"{greek}, {greek}; {text}$",
    # ur"{greek}, {see} {greek}$",
    # ur"{greek}, {text}$",
    # ur"{greek},- {greek} {gloss}; {gloss}$",
    # ur"{greek},- {greek}$",
    # ur"{greek}- \(cp\. Lat\. {latin}-\) inseparable prefix signifying {gloss}, {greek} via {greek}- as in the 2 aor\. {greek}$",
    # ur"{greek}- \(cp\. the gen\. {greek} of {greek} {gloss}\), fr\. {greek} \+suffix- {greek}$",
    # ur"{greek}- \(of complex derivation\) \+{greek}- \(cp\. {greek} {gloss}\)$",
    # ur"{greek}- \({see} prec\.\)$",
    # ur"{greek}- intensive, {greek}; {gloss}$",
    # ur"{greek}-, {greek} \(cp\. {greek}\) {gloss}; {gloss} in var\. senses$",
    # ur"{greek}-, {greek} \({greek}\) fr\. {greek}$",
    # ur"{greek}-, {greek} fr\. {greek}$",
    # ur"{greek}-, {greek} {gloss}, cp\. {greek}$",
    # ur"{greek}-, {greek} {gloss}; {gloss}, then {gloss}$",
    # ur"{greek}-, {greek}$",
    # ur"{greek}-,- {greek}$",
    # ur"{greek}; =next entry$",
    # ur"{greek}; =older {greek} in same sense$",
    # ur"{greek}; ={greek} {gloss}$",
    # ur"{greek}; ={greek}$",
    # ur"{greek}; a late form for {greek} {gloss}$",
    # ur"{greek}; act\. {gloss}, mid\. {gloss} or {gloss}, pass\. {gloss}$",
    # ur"{greek}; antonym {greek}$",
    # ur"{greek}; any {gloss} or {gloss}$",
    # ur"{greek}; basic idea {gloss} as of {text}, then {gloss} or {gloss} as of {text}$",
    # ur"{greek}; by- form of the older {greek} {gloss}, also {gloss}$",
    # ur"{greek}; commonly used in the Mediterranean world in sense of {gloss} {text}$",
    # ur"{greek}; condition of {gloss} as bondage to one’s owner, then in ext\. senses$",
    # ur"{greek}; contrast {greek}$",
    # ur"{greek}; contrast {greek}; {gloss}$",
    # ur"{greek}; cp\. {greek} {gloss}$",
    # ur"{greek}; cp\. οἱ {greek} {gloss} {text}$",
    # ur"{greek}; dim\. of {greek} \(a comparable formation in English would be {gloss}\)$",
    # ur"{greek}; dim\. of {greek}, cp\. {greek}; {gloss}$",
    # ur"{greek}; early writers:{text}, later Gk\. in a more general sense of {gloss}$",
    # ur"{greek}; freq\. in ins\. and pap\. of public servants$",
    # ur"{greek}; in ancient Gk\. in var\. senses of a {gloss}, such as {text}$",
    # ur"{greek}; in both a bad sense {gloss} and a good sense {gloss}$",
    # ur"{greek}; in Gr\.- Rom\. world with focus on {gloss}$",
    # ur"{greek}; in Hom\. {gloss}, then gener\. {gloss}$",
    # ur"{greek}; like {greek}, δ\. can connote {text}$",
    # ur"{greek}; one item in a {greek} {gloss}$",
    # ur"{greek}; only in biblical usage$",
    # ur"{greek}; prim\. a kinship term {gloss}$",
    # ur"{greek}; prim\. {gloss}, then {gloss}, {gloss}$",
    # ur"{greek}; the form with accent on the second syllable signifies {gloss}, with accent on the final syllable {gloss}$",
    # ur"{greek}; the nt\. pl\. {greek} {greek} is used occasionally$",
    # ur"{greek}; the suffix- {greek} may have affinity with {greek}, {greek} {gloss}, and related terms; {gloss}$",
    # ur"{greek}; tr\. {gloss}$",
    # ur"{greek}; whether {greek} or {greek} is the original sp\. is debatable$",
    # ur"{greek}; {gloss} then concretely {gloss}$",
    # ur"{greek}; {gloss} {text}, {text} {gloss} {text}$",
    # ur"{greek}; {gloss}$",
    # ur"{greek}; {gloss}, but usually pl\. {greek} {gloss}$",
    # ur"{greek}; {gloss}, esp\. {text}$",
    # ur"{greek}; {gloss}, freq\. {text}$",
    # ur"{greek}; {gloss}, in ext\. sense {gloss} ={gloss}$",
    # ur"{greek}; {gloss}, then gen\. {gloss}$",
    # ur"{greek}; {gloss}, then {gloss}$",
    # ur"{greek}; {gloss}, then {text} or {gloss}$",
    # ur"{greek}; {gloss}, {gloss}$",
    # ur"{greek}; {gloss}, {text}$",
    # ur"{greek}; {gloss}, {text}:{gloss}$",
    # ur"{greek}; {gloss}; cp\. {greek} {text} {gloss}$",
    # ur"{greek}; {gloss}; {text}$",
    # ur"{greek}; {greek} is the regular form$",
    # ur"{greek}; {half-gloss}$",
    # ur"{greek}; {text}$",
    # ur"{greek}; {text}, hence, {gloss}$",
    # ur"{greek}\., {greek} \({greek} {gloss}\) {gloss}$",
    ur"{see} {greek}$",
    ur"{see} {prec} {greek}- entries and two next entries$",
    ur"{see} {prec} {greek}- entries; the act\., which is not used in NT ={gloss}$",
    ur"{text} ={greek} {greek} {gloss}$",
    ur"{text}; cp\. the pf\. of Homeric {greek}:{greek}$",
    ur"{text}; {text} {greek} {gloss} {text} {gloss}; {text} {gloss}$",
    # ur"ἀ- \(ἁ-\) copul\., {greek}$",
    # ur"ἀ- copul\., {greek} {gloss} ={gloss}$",
    # ur"ἀ- copul\., {greek} {gloss}$",
    # ur"ἀ- priv, {greek}$",
    # ur"ἀ- priv\. \(ἁ- by metathesis of aspiration\), {greek}, otherwise a word of uncertain orig\.$",
    # ur"ἀ- priv\., cp\. {greek}, {text}$",
    # ur"ἀ- priv\., fr\. {greek} via the fut\. mid\. form of {greek}:{greek}$",
    # ur"ἀ- priv\., {greek} =Attic {greek} s$",
    # ur"ἀ- priv\., {greek} ={greek} {gloss} {text}; {gloss}$",
    # ur"ἀ- priv\., {greek} \({greek}, {greek} {gloss}\) {gloss} or \({greek}, {greek} {gloss} fr\. {greek} {gloss}\) {gloss}$",
    # ur"ἀ- priv\., {greek} \({greek}, {greek}\) {gloss}$",
    # ur"ἀ- priv\., {greek} \({greek}, {greek}\) {gloss}; {gloss}$",
    # ur"ἀ- priv\., {greek} fr\. {greek}$",
    # ur"ἀ- priv\., {greek} via 2 aor\. {greek}; {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss} fr\. {greek} {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss} fr\. {greek}$",
    # ur"ἀ- priv\., {greek} {gloss} fr\. {greek}; lit\. {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss} fr\. {greek}; {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss}, cp\. {greek}$",
    # ur"ἀ- priv\., {greek} {gloss}, esp\. {text}$",
    # ur"ἀ- priv\., {greek} {gloss}, fr\. {greek} via {greek} {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss}, freq\. in 3 sg\. {greek}$",
    # ur"ἀ- priv\., {greek} {gloss}, {text}; {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss}; cp\. {greek} {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss}; {gloss}$",
    # ur"ἀ- priv\., {greek} {gloss}; {gloss}, hence {gloss}$",
    # ur"ἀ- priv\., {greek}$",
    # ur"ἀ- priv\., {greek}, cp\. {greek} and {greek}$",
    # ur"ἀ- priv\., {greek}, q\. v\., in sense of {gloss}; {text}$",
    # ur"ἀ- priv\., {greek}, {greek} {gloss} fr. {greek}$",
    # ur"ἀ- priv\., {greek}, {greek} {gloss}, cp\. {greek} {gloss}$",
    # ur"ἀ- priv\., {greek}, {greek}$",
    # ur"ἀ- priv\., {greek}; {gloss}$",
    # ur"ἀ- priv\., {greek}; {gloss}, {text} {gloss} {text}$",
    # ur"ἀ- priv\., {greek}; {text}$",
    # ur"ἀ\.- priv\., {greek} \(used in the phrase {greek} {greek} {gloss}\) fr\. {greek}$",
    # ur"ἀ\.- priv\., {greek}, cp\. {greek}$",
    # ur"ἁ- copul\. {gloss} =Skt\. {skt}-, cp\. {greek} and oblique forms$",
    # ur"ἁ- copul\., {greek} \(etym\. complex, with idea of {gloss}\) as in {greek} {gloss}; {gloss}$",
    # ur"ἐκ- intensive, {greek} {gloss}$",
    # ur"ἐκ- intensive, {greek}$",
    # ur"ἡ {greek} {gloss} and ὁ {greek} {gloss}, fr\. a common root:cp\. Lat\. {latin} {gloss}$",
    # ur"ὁ {greek} {gloss}$",

    ## do-not contain greek

    # ur"(orig|etym)\. (complex|not determined|obscure|unclear|uncertain|unknown)$",
    # ur"=Lat\. {latin} {gloss}$",
    # ur"=Lat\. {latin} {latin}$",
    # ur"=Lat\. {latin}$",
    # ur"=next entry$",
    # ur"=Skt\. {skt} {gloss}$",
    # ur"=Skt\. {skt}$",
    # ur"a city named in honor of Antipater, procurator of Judea under Julius Caesar$",
    # ur"a common name in the Greco- Roman world$",
    # ur"a common name$",
    # ur"a common name, {text}$",
    # ur"a Greek name$",
    # ur"a Rom\. cognomen; cp\. Lat\. {latin} {gloss}$",
    # ur"acc\. to Herodotus 4, 199, a Cyrenaic word$",
    # ur"an onomatopoetic word ={gloss}, sim\. Lat\. {latin}; {text} {gloss}$",
    # ur"apparently of foreign orig\.$",
    # ur"apparently of Heb\. orig\.$",
    # ur"Aram\. ={text}; {see} explanation {ref}$",
    # ur"Aram\. name {gloss}$",
    # ur"Aram\. place name$",
    # ur"Aram\. term ={gloss}$",
    # ur"Aram\. word of uncertain mng\.$",
    # ur"Aram\. {gloss}$",
    # ur"Aram\. {gloss}; a common name$",
    # ur"Aram\. {gloss}; cp\. next$",
    # ur"Aram\.$",
    # ur"Aram\., perh\. {half-gloss}$",
    # ur"Aram\., prob\. ={text} {gloss}, i\. e\. {text}$",
    # ur"as loanword in Lat\. {latin} {gloss}$",
    # ur"assoc\. w\. the Heb\. name {text}, of uncertain mng\., {ref}; {ref}$",
    # ur"basic sense {gloss}$",
    # ur"breathing mark for the ο varies in editions, smooth in Homer$",
    # ur"composed of Heb\. words meaning {gloss} and {gloss}$",
    # ur"Coptic loanword$",
    # ur"cp\. Lat\. {latin} \({text}\) {gloss}$",
    # ur"cp\. Lat\. {latin} {gloss} {text}$",
    # ur"cp\. Lat\. {latin} {gloss}$",
    # ur"cp\. Lat\. {latin} {gloss}, also {gloss}$",
    # ur"cp\. Lat\. {latin} {gloss}, e. g. {text}$",
    # ur"cp\. Lat\. {latin} {gloss}; fut\. {latin}$",
    # ur"cp\. Lat\. {latin} {gloss}; prim\. {gloss} {text}, then {gloss}$",
    # ur"cp\. Lat\. {latin}$",
    # ur"cp\. next$",
    # ur"cp\. older German {latin} {gloss} {text}$",
    # ur"cp\. Skt\. {skt} {gloss}$",
    # ur"cp\. Skt\. {skt} {gloss}, Lat\. {latin}$",
    # ur"cp\. Skt\. {skt}, for oblique cases cp\. Skt\. {skt}$",
    # ur"cp\. {prec} entries$",
    # ur"cp\. {prec}$",
    # ur"derivation undetermined, but a root signifying {gloss} or {gloss} has claimed attention$",
    # ur"Egyptian base w\. Heb\. assoc\.$",
    # ur"etym\. (complex|unclear|uncertain); {gloss}$",
    # ur"etym\. complex, cp\. prec\.$",
    # ur"etym\. complex, cp\. {text} {gloss}$",
    # ur"etym\. complex; as adv\. {gloss}, as conj\. {gloss}$",
    # ur"etym\. complex; in Homer only in sense of {gloss}$",
    # ur"etym\. complex; prim\. {gloss} {text}$",
    # ur"etym\. complex; {gloss} \(Hom\.\), then {gloss}$",
    # ur"etym\. complex; {gloss}, also {gloss} as distinguished from those of highter status$",
    # ur"etym\. complex; {gloss}, also {gloss}$",
    # ur"etym\. complex; {gloss}, then metaph\. {gloss}$",
    # ur"etym\. complex; {gloss}, {gloss} {text}$",
    # ur"etym\. complex; {gloss}, {text} {gloss}$",
    # ur"etym\. complex; μ\. embraces the duality of a plant {gloss} and animal {gloss}$",
    # ur"etym\. not established, but assoc\. w\. a flexible tree such as {gloss} \(Lat\. {latin}\) has been proposed$",
    # ur"etym\. uncertain, cp\. Lat\. {latin} \(freq\. used of {gloss} and prob\. borrowed fr\. the Gk\.\)$",
    # ur"etym\. uncertain, perh\. a foreign loanword; {text}$",
    # ur"etym\. uncertain; orig\. {gloss}, then {gloss}$",
    # ur"etym\. uncertain; {text}$",
    # ur"etym\. uncertain; {text}:{text}$",
    # ur"etym\. unclear; two major significations:{gloss} with raw materials, {gloss} esp\. of athletic exercise$",
    # ur"etym\. undetermined; freq\. in Homer of {gloss} or {gloss} {text}$",
    # ur"etym\. unknown, Lat\. {latin} is a loanword$",
    # ur"etymol\. unknown$",
    # ur"fr\. a conjectured root shared by Lat\. {latin} {gloss}$",
    # ur"fr\. a root to which Lat\. {latin} {gloss} is related$",
    # ur"fr\. a source shared by Lat\. {latin} {gloss}$",
    # ur"Grecized form of Heb\. {gloss}$",
    # ur"Heb\. /Aram\. {gloss} or {gloss}$",
    # ur"Heb\. \(={text}\)$",
    # ur"Heb\. name$",
    # ur"Heb\. name, hence {gloss}$",
    # ur"Heb\. prob\. in sense of {gloss}$",
    # ur"Heb\. {gloss} or {gloss}$",
    # ur"Heb\. {gloss}$",
    # ur"Heb\. {gloss}$",
    # ur"Heb\.$",
    # ur"Heb\., of uncertain etymology$",
    # ur"Heb\., prob\. means {gloss}$",
    # ur"Heb\., prob\. {gloss}$",
    # ur"Heb\.; cp\. modern Gk\. ἀ\. {gloss}$",
    # ur"Heb\.; {gloss}$",
    # ur"Heb\.; {text} {gloss}$",
    # ur"identical with Gothic- k$",
    # ur"IE from a root meaning {gloss} with idea of {text}$",
    # ur"IE$",
    # ur"IE, =Lat\. {latin}$",
    # ur"IE, cp\. Lat\. {latin} {gloss}$",
    # ur"IE, cp\. Lat\. {latin}$",
    # ur"IE; mostly used by poets$",
    # ur"IE; var\. senses in Gk\. lit\.$",
    # ur"IE; {gloss} {text}$",
    # ur"IE; {gloss}, {text}$",
    # ur"IE; {text}:{text}$",
    # ur"in Gk\. lit\. {text}$",
    # ur"Indo- Germanic origin =Lat\. {latin}$",
    # ur"Lat\. loanword {latin} \({latin} {half-gloss}\), {text}$",
    # ur"Lat\. loanword {latin} {gloss}, fr\. {latin} {gloss}$",
    # ur"Lat\. loanword:{gloss}, {text} ={text}$",
    # ur"Lat\. loanword:{latin} {gloss}$",
    # ur"Lat\. orig\.$",
    # ur"Lat\. orig\., cp\. the masc\. {latin}; {text}$",
    # ur"Lat\. orig\.; {text}$",
    # ur"Lat\. {gloss}$",
    # ur"Lat\. {latin} {gloss}$",
    # ur"Lat\. {latin} {gloss}, also {text}$",
    # ur"Lat\. {latin} {gloss}; {gloss}; {text}$",
    # ur"Lat\. {latin}, {text}$",
    # ur"Lat\.; {gloss}, then {text}$",
    # ur"Latin loanword {gloss}$",
    # ur"Latin loanword:{latin} {gloss}, as measurement of distance 1,000 passus or ‘paces’ =8 stadia of about 192 m. each, or slightly less than our mile$",
    # ur"loanword in Lat\. {latin} {gloss}$",
    # ur"MT",
    # ur"multivalent verb since Hom\.$",
    # ur"name common also in Lat\. {gloss}$",
    # ur"name found in Aegean inscriptions$",
    # ur"name of {text}$",
    # ur"named after {text}$",
    # ur"not of Lat\. orig\., but cp\. Lat\. {latin} \(in turn ascribed to Semitic orig\.\) {gloss}$",
    # ur"of Dravidian origin$",
    # ur"of Heb\. derivation$",
    # ur"of Oriental origin, prob\. via Egypt; {gloss}, {text}$",
    # ur"of Sanskrit origin, cp\. Lat\. {latin} {gloss}$",
    # ur"of Semitic orig\.$",
    # ur"of uncertain etymology; the mng\. {gloss} has not gone unchallenged$",
    # ur"onomatopoetic word$",
    # ur"orig\. uncertain; {text}$",
    # ur"orig\. unclear; {text} {gloss}$",
    # ur"orig\. unclear; {text}$",
    # ur"orig\. undetermined; {text}$",
    # ur"origin debated; {gloss}, later in ext\. sense$",
    # ur"origin uncertain; primary sense:{gloss} w\. focus on {text}$",
    # ur"perh\. related to prec\. by dissimilation or change of consonant$",
    # ur"Persian loanword rendered {gloss}$",
    # ur"primitive word, cp\. Lat\. {latin} {gloss}$",
    # ur"prob\. of foreign origin$",
    # ur"ptc\. of a lost verb meaning {gloss}$",
    # ur"related to a Heb\. word for {gloss}$",
    # ur"Roman cognomen$",
    # ur"Semitic assoc\.; frequently referenced by Herodotus$",
    # ur"Semitic orig\.$",
    # ur"Skr\. assoc\., cp\. Lat\. {gloss} \({gloss}\)$",
    # ur"Skt\. =Lat\. {latin} {gloss}$",
    # ur"Skt\. assoc; most freq\. in ref\. to {text}$",
    # ur"Skt\. assoc\. in sense of {gloss}$",
    # ur"Skt\. assoc\.$",
    # ur"Skt\. assoc\., cp\. Lat\. {latin} {gloss}$",
    # ur"Skt\. assoc\.; cp\. Lat\. {latin} {gloss} and its transferred sense {gloss}$",
    # ur"Skt\. assoc\.; in Hom\. {gloss} in various occupations and social roles, and as {gloss}$",
    # ur"Skt\. assoc\.; {gloss}, {text}$",
    # ur"Skt\. assoc\.; {text} \(esp\. of {text}\) {gloss}, {text} {gloss}$",
    # ur"Skt\. assoc\.; {text} as in {gloss} {text} as in {gloss}$",
    # ur"Skt\. via Heb\.$",
    # ur"Skt\. {skt} {gloss}$",
    # ur"Skt\. {skt} {gloss}$",
    # ur"Skt\. {skt} {gloss}, cp\. Lat\. {latin} {gloss}$",
    # ur"Skt\. {skt} {gloss}, cp\. next$",
    # ur"Skt\. {skt} {gloss}, Lat\. {latin} {gloss}; prim\. in local sense {gloss}$",
    # ur"Skt\. {skt} · {gloss}$",
    # ur"Skt\., cp\. Lat\. {latin}; {gloss} so as to {gloss}, also {gloss}$",
    # ur"Skt\.; {text}$",
    # ur"Skt\.; {text}, {gloss}$",
    # ur"the form and textual history of this name is complex$",
    # ur"the prep\. functions intensively {gloss}$",
    # ur"the time of the day for δ\. varies in Gk\. lit, but eventually δ\. chiefly refers to {gloss}$",
    # ur"the verbal aspect of 2b in prec\.$",
    # ur"{gloss}$",
    # ur"{see} next entry on the etymology$",
    # ur"{see} next$",
    # ur"{see} {prec} entry$",
    # ur"{see} {prec}$",
    # ur"{text} {gloss}$",
    # ur"{text}$",
    # ur"{text}; {gloss}$",
]

compiled_regexes = []

for regex in regexes:
    for name, substitution in regex_templates.items():
        regex = re.sub("{{{}}}".format(name), substitution, regex)
    compiled_regexes.append(re.compile(regex))

danker = load_yaml("../data-cleanup/danker-concise-lexicon/components.yaml")

derivation = load_yaml("derivation.yaml")

skipped = 0
existing = 0
added = 0
for lexeme, metadata in sorted_items(danker):
    components = metadata["components"].strip()

    matched = False
    for compiled_regex in compiled_regexes:
        if compiled_regex.match(components):
            matched = True
    if not matched:
        skipped += 1
        continue

    print "{}:".format(lexeme.encode("utf-8"))
    if lexeme in derivation:
        if derivation[lexeme]:

            def q(key):
                if key in derivation[lexeme]:
                    if isinstance(derivation[lexeme][key], list):
                        print "    {}:".format(key)
                        for item in derivation[lexeme][key]:
                            print "        - {}".format(item.encode("utf-8"))
                    else:
                        print "    {}: {}".format(key, derivation[lexeme][key].encode("utf-8"))

            q("derivation")
            q("equal")
            q("see")
        existing += 1
    else:
        print "    {}:".format("derivation")
        print "        - {}@".format(components.encode("utf-8"))
        added += 1


print >>sys.stderr, "{} skipped; {} existing; {} added".format(skipped, existing, added)
